import { randomUUID } from "node:crypto";
import { db, WishlistItem, ExchangeRate, Reservation } from "astro:db";

// https://astro.build/db/seed
export default async function seed() {
  // Insert exchange rates (to RUB)
  await db.insert(ExchangeRate).values([
    {
      id: 1,
      fromCurrency: "USD",
      toCurrency: "RUB",
      rate: 82,
      updatedAt: new Date(),
    },
    {
      id: 2,
      fromCurrency: "EUR",
      toCurrency: "RUB",
      rate: 98,
      updatedAt: new Date(),
    },
    {
      id: 3,
      fromCurrency: "GBP",
      toCurrency: "RUB",
      rate: 112,
      updatedAt: new Date(),
    },
    {
      id: 4,
      fromCurrency: "AUD",
      toCurrency: "RUB",
      rate: 56,
      updatedAt: new Date(),
    },
    {
      id: 5,
      fromCurrency: "INR",
      toCurrency: "RUB",
      rate: 1,
      updatedAt: new Date(),
    },
  ]);

  await db.insert(WishlistItem).values([
    {
      id: 1,
      title: "The Florida Project Limited Edition 4K UHD",
      titleRu: "Проект Флорида 4K UHD, лимитированное издание",
      price: "$64",
      imageUrl: "second-sight-florida-project.webp",
      //TODO: rewrite
      description:
        "Sean Baker's pastel-colored poverty. Kids, motels, and broken dreams",
      descriptionRu:
        "Пастельная нищета Шона Бейкера. Дети, мотели и разбитые мечты",
      url: "https://www.ebay.com/itm/306576066529",
      category: "blu-ray",
      priority: "medium",
      received: false,
    },
    {
      id: 2,
      title: "Tangerine Limited Edition Blu-ray",
      titleRu: "Мандарин на Blu-ray, лимитированное издание",
      price: "£25",
      imageUrl: "second-sight-tangerine.webp",
      //TODO: rewrite
      description:
        "Shot on iPhone 5s. Trans sex workers in LA on Christmas Eve",
      descriptionRu:
        "Снято на iPhone 5s. Транс-секс-работницы в ЛА в канун Рождества",
      url: "https://secondsightfilms.co.uk/products/tangerine-limited-edition-blu-ray-pre-order-available-december-19th",
      category: "blu-ray",
      priority: "medium",
      received: false,
    },
    {
      id: 5,
      title: "Titanium Band for Apple Watch Ultra",
      titleRu: "Титановый ремешок для Apple Watch Ultra",
      price: "$249",
      imageUrl: "apple-watch-band.webp",
      url: "https://nomadgoods.com/products/titanium-band-46mm-49mm-natural-hardware-v3",
      description: "A band to pretend I’m not broke",
      descriptionRu: "Ремешок, чтобы притворяться, что я не броук",
      category: "other",
      priority: "low",
      received: false,
    },
    {
      id: 6,
      title: "Astro Bot Soundtrack Vinyl",
      titleRu: "Саундтрек Astro Bot на виниле",
      price: "$39",
      imageUrl: "astrobot-vinyl.webp",
      url: "https://www.fangamer.com/collections/astro-bot/products/astro-bot-2024-vinyl",
      //TODO: rewrite
      description: "Robo, robo, robo",
      descriptionRu: "Роботик, роботик, роботик",
      category: "vinyl",
      priority: "low",
      received: false,
    },
    {
      id: 7,
      title: "Celeste Desk Mat",
      titleRu: "Коврик для стола Celeste",
      price: "$28",
      imageUrl: "celeste-deskmat.webp",
      url: "https://www.fangamer.com/collections/celeste/products/celeste-desk-mat-skies",
      description: "Large desk mat with Celeste artwork",
      descriptionRu: "Большой коврик для стола с артом из Celeste",
      category: "merch,home",
      priority: null,
      received: true,
    },
    {
      id: 8,
      title: "TPOB XO Clipper (Slime Edition)",
      titleRu: "Машинка для стрижки TPOB XO (Slime)",
      price: "$74",
      imageUrl: "tpob-xo-clipper.webp",
      url: "https://tpobusa.com/collections/clippers/products/xo-clipper-slime",
      description:
        "Professional cordless clipper so I can cut my hair at home and avoid people",
      descriptionRu:
        "Профессиональная беспроводная машинка для стрижки своей головы дома, чтобы избегать людей",
      category: "home",
      priority: "high",
      received: false,
      weight: 3,
    },
    {
      id: 9,
      title: "TPOB Mini Skull (Blackout edition)",
      titleRu: "Электробритва TPOB Mini Skull (Blackout)",
      price: "$45",
      imageUrl: "tpob-mini-skull.webp",
      url: "https://tpobusa.com/collections/shavers/products/blackout-mini-skull",
      description: "Compact electric shaver for travel",
      descriptionRu: "Компактная электробритва в дорогу",
      category: "home",
      priority: "high",
      received: false,
      weight: 2,
    },
    {
      id: 10,
      title: "Hollow Knight Gods & Nightmares Vinyl Soundtrack",
      titleRu: "Саундтрек Hollow Knight: Gods & Nightmares на виниле",
      price: "$29",
      imageUrl: "hollowknight-vinyl.webp",
      url: "https://www.fangamer.com/collections/vinyl-game-soundtracks/products/hollow-knight-gods-nightmares-vinyl-soundtrack",
      //TODO: rewrite
      description:
        "Christopher Larkin's boss themes. For suffering enthusiasts",
      descriptionRu:
        "Темы боссов от Кристофера Ларкина. Для ценителей страданий",
      category: "vinyl",
      priority: "low",
      received: false,
    },
    {
      id: 11,
      title:
        "Hollow Knight Collector's Edition for Nintendo Switch + Wanderer's Journal",
      titleRu:
        "Коллекционное издание Hollow Knight для Nintendo Switch + Журнал Охотника",
      price: "$107",
      imageUrl: "hollowknight-collectors-edition.webp",
      url: "https://www.fangamer.com/products/hollow-knight-game-collectors-edition-nintendo-switch",
      //TODO: rewrite
      description: "Physical copy + lore journal. For the shelf and the soul",
      descriptionRu: "Физическая копия + журнал с лором. Для полки и для души",
      category: "merch",
      priority: "low",
      received: false,
    },
    {
      id: 12,
      title: "Hollow Knight Blanket",
      titleRu: "Плед Hollow Knight",
      price: "$45",
      imageUrl: "hollowknight-blanket.webp",
      url: "https://www.fangamer.com/products/hollow-knight-blanket",
      description: "A blanket to wrap myself in instead of dealing with life",
      descriptionRu:
        "Плед, чтобы завернуться в него вместо того, чтобы разбираться с жизнью",
      category: "merch,home",
      priority: "medium",
      received: false,
    },
    {
      id: 13,
      title: "X Trilogy: Collector's Edition Box Set (4K UHD)",
      titleRu: "Трилогия X: Коллекционное издание (4K UHD)",
      price: "$100",
      imageUrl: "a24-x-trilogy.webp",
      url: "https://shop.a24films.com/products/x-trilogy-collectors-edition",
      //TODO: rewrite
      description:
        "3-disc box set with X, Pearl, MaXXXine — packaging is indecently beautiful",
      descriptionRu:
        "Бокс-сет из 3 дисков с X, Pearl, MaXXXine — упаковка неприлично красивая",
      category: "blu-ray",
      priority: "medium",
      received: false,
    },
    {
      id: 14,
      title: "Possession 4K Limited Edition UHD Blu-ray",
      titleRu: "Одержимая 4K UHD, лимитированное издание",
      price: "$85",
      imageUrl: "second-sight-possesion.webp",
      url: "https://www.ebay.com/itm/326922568960",
      //TODO: rewrite
      description:
        "Isabelle Adjani's legendary breakdown. A cult horror masterpiece",
      descriptionRu: "Легендарный срыв Изабель Аджани. Культовый хоррор-шедевр",
      category: "blu-ray",
      priority: "medium",
      received: false,
    },
    {
      id: 15,
      title: "The Straight Story Blu-ray",
      titleRu: "Простая история на Blu-ray",
      price: "AU$140",

      imageUrl: "imprint-the-straight-story.webp",
      url: "https://www.ebay.com/itm/276396157419",
      description:
        "David Lynch, but calm. A straight story. The only Lynch film I don't have in my collection yet",
      descriptionRu:
        "Дэвид Линч, но спокойный и простой. Единственный его фильм которого у меня еще нет в коллекции",
      category: "blu-ray",
      priority: "medium",
      received: false,
    },
    {
      id: 16,
      title: "Tokyo Decadence Blu-ray",
      titleRu: "Токийский декаданс на Blu-ray",
      price: "$31",
      imageUrl: "tokyo-decadence.webp",
      url: "https://www.ebay.com/itm/375499327864",
      //TODO: rewrite
      description: "Ryu Murakami's erotic drama. Tokyo's underground desires",
      descriptionRu:
        "Эротическая драма Рю Мураками. Тёмные желания токийского андеграунда",
      category: "blu-ray",
      priority: "low",
      received: false,
    },
    {
      id: 17,
      title: "555 Soundtrack Vinyl LP",
      titleRu: "Саундтрек 555 на виниле, очень редкий",
      price: "$57",
      imageUrl: "555-vinyl.webp",
      url: "https://www.ebay.com/itm/176437398555",
      description: "Limited to 50 copies. Unfortunately, I need this",
      descriptionRu: "Лимитированное издание, тираж 50 копий. Это мне надо.",
      category: "vinyl",
      priority: "medium",
      received: false,
    },
    {
      id: 18,
      title: "Nekromantik Soundtrack Vinyl LP + EP",
      titleRu: "Саундтрек Некромантик на виниле, очень редкий",
      price: "€300",
      imageUrl: "nekromantik-vinyl.webp",
      url: "https://www.ebay.com/itm/134673382645",
      description:
        "Absurdly rare and absurdly expensive. Unfortunately, I need this",
      descriptionRu:
        "Нелепо редкий и нелепо дорогой. К сожалению, это мне нужно",
      category: "vinyl",
      priority: "medium",
      received: false,
    },
    {
      id: 19,
      title: "Nekromantik T-Shirt",
      titleRu: "Футболка Nekromantik",
      price: "$25",
      imageUrl: "nekromantik-tshirt.webp",
      url: "https://www.ebay.com/itm/135116828682",
      //TODO: rewrite
      description: "For those who get it. A great conversation stopper",
      descriptionRu:
        "Для тех, кто понимает. Отличный способ прекратить разговор",
      category: "merch,clothing",
      priority: "medium",
      received: false,
    },
    {
      id: 20,
      title: "Vans Sk8-Hi",
      titleRu: "Кеды Vans Sk8-Hi",
      price: "$145",
      imageUrl: "vans-sk8hi.avif",
      url: "https://www.vans.com/en-us/p/shoes/icons/sk8-hi-5325/sk8-hi-waterproof-insulated-shoe-VN000DAQBKA?size=8.5+Men+%3D+10.0+Women",
      description: "Waterproof and insulated — for winter",
      descriptionRu: "С водозащитой и утеплением — на зиму",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 21,
      title: "Jordan Club Hat",
      titleRu: "Кепка Jordan Club",
      price: "$25",
      imageUrl: "jordan-club-hat.avif",
      url: "https://www.nike.com/t/jordan-club-unstructured-curved-bill-hat-TR8rQt/HQ1963-010",
      description: "Basic cap",
      descriptionRu: "Базовая кепка",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 22,
      title: "Philips Sonicare 9900 Prestige",
      titleRu: "Электрическая зубная щётка Philips Sonicare",
      price: "$300",
      imageUrl: "philips-sonicare-diamondclean.webp",
      url: "https://a.co/d/49pcu6S",
      description: "The fancy toothbrush",
      descriptionRu: "Модная зубная щётка",
      category: "home",
      priority: "medium",
      received: false,
    },
    {
      id: 23,
      title: "Yung Lean — Warlord (White Vinyl LP)",
      titleRu: "Yung Lean — Warlord (белый винил, лимитированное издание)",
      price: "$70",
      imageUrl: "yung-lean-warlord-vinyl.webp",
      url: "https://www.discogs.com/sell/item/1950442079",
      description: "My favorite Yung Lean album. Pure 2016 nostalgia",
      descriptionRu: "Мой любимый альбом Yung Lean, ностальгия по 2016",
      category: "vinyl",
      priority: "medium",
      received: false,
    },
    {
      id: 24,
      title: "Funko POP Twin Peaks Laura Palmer",
      titleRu: "Funko POP Twin Peaks (Лора Палмер)",
      price: "$120",
      imageUrl: "funko-pop-laura-palmer.jpg",
      url: "https://a.co/d/fqFZyLg",
      description: "Extremely rare. And yes, that’s the whole reason.",
      descriptionRu: "Крайне редкая, но в этом вся суть",
      category: "merch",
      priority: "medium",
      received: false,
    },
    {
      id: 25,
      title: "Boy Harsher — Lesser Man EP (Red Translucent Vinyl)",
      titleRu:
        "Boy Harsher — Lesser Man EP (красный винил, лимитированное издание)",
      price: "€50",
      imageUrl: "boy-harsher-lesser-man-vinyl.jpg",
      url: "https://www.discogs.com/sell/item/2961810748",
      //TODO: rewrite
      description: "Dark synth duo. Pain you can dance to",
      descriptionRu: "Мрачный синт-дуэт. Боль, под которую можно танцевать",
      category: "vinyl",
      priority: "medium",
      received: false,
    },
    {
      id: 26,
      title: "Philips Sonicare Power Flosser 3000",
      titleRu: "Ирригатор Philips Sonicare",
      price: "$70",
      imageUrl: "philips-sonicare-flosser.jpg",
      url: "https://a.co/d/hrfsFUQ",
      //TODO: rewrite
      description: "Water flossing. For teeth that deserve better",
      descriptionRu: "Ирригатор. Для зубов, которые заслуживают лучшего",
      category: "home",
      priority: "medium",
      received: false,
    },
    {
      id: 27,
      title: "Adidas Terrex Free Hiker 2.0 Low GORE-TEX",
      titleRu: "Кроссовки Adidas Terrex",
      price: "$180",
      imageUrl: "terrex-shoes.avif",
      url: "https://www.adidas.com/us/terrex-free-hiker-2.0-low-gore-tex-hiking-shoes/IH0672.html?forceSelSize=9",
      description: "I need sneakers for city, hiking, and shitty weather",
      descriptionRu:
        "Нужны кроссы и для города, и для хайкинга, и для всратой погоды",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 28,
      title: "Adidas Beanie",
      titleRu: "Шапка Adidas",
      price: "$17",
      imageUrl: "adidas-beanie.avif",
      url: "https://www.adidas.com/us/unisex-trefoil-beanie/JL1081.html",
      description: "Basic beanie",
      descriptionRu: "Базовая шапка",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 29,
      title: "RIPNDIP Boxers 3 Pack",
      titleRu: "Боксеры RIPNDIP 3 шт.",
      price: "$36",
      imageUrl: "ripndip-boxers.webp",
      url: "https://www.ripndipclothing.com/en-kz/collections/holiday-2025/products/smd-boxers-3-pack-multi",
      //TODO: rewrite
      description:
        "Middle finger cat on underwear. Self-expression where it counts",
      descriptionRu: "Кот с факом на трусах. Самовыражение там, где это важно",
      category: "clothing",
      priority: "medium",
      received: false,
    },
    {
      id: 30,
      title: "RIPNDIP Longsleeve",
      titleRu: "Лонгслив RIPNDIP",
      price: "$44",
      imageUrl: "ripndip-long-sleave.webp",
      url: "https://www.ripndipclothing.com/collections/holiday-2025/products/the-happiest-cat-ls-black",
      //TODO: rewrite
      description:
        "Long sleeve with the infamous cat. For layering and attitude",
      descriptionRu:
        "Лонгслив с легендарным котом. Для многослойности и настроения",
      category: "clothing",
      priority: "medium",
      received: false,
    },
    {
      id: 31,
      title: "RIPNDIP Knit Sweater",
      titleRu: "Свитер RIPNDIP",
      price: "$80",
      imageUrl: "ripndip-knit-sweater.webp",
      url: "https://www.ripndipclothing.com/collections/holiday-2025/products/out-of-this-world-knit-sweater-black",
      //TODO: rewrite
      description: "Cozy knit with RIPNDIP vibes. Warm and weird",
      descriptionRu: "Уютный вязаный свитер в стиле RIPNDIP. Тёплый и странный",
      category: "clothing",
      priority: "medium",
      received: false,
    },
    {
      id: 32,
      title: "Vans Skate Half Cab",
      titleRu: "Кеды Vans Skate Half Cab",
      price: "$85",
      imageUrl: "vans-skate-half-cab.avif",
      url: "https://www.vans.com/en-us/p/shoes/icons/half-cab-1992/skate-half-cab-shoe-VN0A5FCDY28?size=8.5+Men+=+10.0+Women",
      //TODO: rewrite
      description: "Classic skate silhouette. Steve Caballero's legacy",
      descriptionRu: "Классический скейт-силуэт. Наследие Стива Кабальеро",
      category: "clothing",
      priority: "medium",
      received: false,
    },
    {
      id: 33,
      title: "Philips Norelco Head Shaver Pro 7000 Series",
      titleRu: "Электробритва для головы Philips Norelco",
      price: "$85",
      imageUrl: "philips-head-shaver.webp",
      url: "https://www.usa.philips.com/c-p/HS7980_40/head-shaver-pro-7000-series-advanced-shaver-with-90-min-runt~",
      //TODO: rewrite
      description: "For the bald look. Quick and clean head shaving",
      descriptionRu: "Для лысого образа. Быстрое и чистое бритьё головы",
      category: "home",
      priority: "high",
      received: false,
      weight: 1,
    },
    {
      id: 34,
      title: "Calvin Klein 3-Pack T-Shirt",
      titleRu: "Набор футболок Calvin Klein 3 шт.",
      price: "$37",
      imageUrl: "ck-3-pack-t-shirt.webp",
      url: "https://www.calvinklein.us/en/underwear/men/undershirt-tank/cotton-classics-3-pack-classic-fit-crewneck-t-shirt/NB4051-UB1.html",
      //TODO: rewrite
      description: "Basic white tees. The foundation of any wardrobe",
      descriptionRu: "Базовые белые футболки. Основа любого гардероба",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 35,
      title: "Calvin Klein Tech Pique T-Shirt",
      titleRu: "Футболка Calvin Klein",
      price: "$35",
      imageUrl: "ck-tech-pique-t-shirt.webp",
      url: "https://www.calvinklein.us/en/men/apparel/tops/tech-pique-t-shirt/4LD298G-UB1.html",
      //TODO: rewrite
      description: "Technical fabric tee. Minimal and functional",
      descriptionRu:
        "Футболка из технологичной ткани. Минимализм и функциональность",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 36,
      title: "Adidas Oversized Tee (2 pcs)",
      titleRu: "Оверсайз футболка Adidas (2 шт)",
      price: "$48",
      imageUrl: "adidas-oversized-tee.avif",
      url: "https://www.adidas.com/us/trefoil-essentials-oversized-tee/JD0349.html",
      //TODO: rewrite
      description: "Oversized fit with the classic trefoil. Comfy everyday tee",
      descriptionRu:
        "Оверсайз с классическим трилистником. Удобная повседневная футболка",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 37,
      title: "Adidas Pants",
      titleRu: "Штаны Adidas",
      price: "$48",
      imageUrl: "adidas-pants.avif",
      url: "https://www.adidas.com/us/trefoil-essentials-pants/IY7361.html?forceSelSize=XS",
      //TODO: rewrite
      description: "Relaxed joggers for home and errands",
      descriptionRu: "Свободные джоггеры для дома и по делам",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 38,
      title: "Adidas Fleece Pants",
      titleRu: "Флисовые штаны Adidas",
      price: "$50",
      imageUrl: "adidas-3-stripes-pants.avif",
      url: "https://www.adidas.com/us/essentials-3-stripes-fleece-pants/KE7273.html?forceSelSize=XS",
      //TODO: rewrite
      description: "Fleece joggers with the iconic stripes. Warm and classic",
      descriptionRu:
        "Флисовые джоггеры с культовыми полосками. Тёплые и классические",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 39,
      title: "Adidas Sweatshirt",
      titleRu: "Свитшот Adidas",
      price: "$50",
      imageUrl: "adidas-sweatshirt.avif",
      url: "https://www.adidas.com/us/soft-lux-sweatshirt/KF0485.html?pr=pdpctl_rr&slot=3&rec=ds&forceSelSize=S",
      //TODO: rewrite
      description: "Premium soft fabric. For cozy days",
      descriptionRu: "Премиальная мягкая ткань. Для уютных дней",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 40,
      title: "Adidas Hoodie",
      titleRu: "Худи Adidas",
      price: "$36",
      imageUrl: "adidas-hoodie.avif",
      url: "https://www.adidas.com/us/trefoil-essentials-hoodie/IY4930.html",
      //TODO: rewrite
      description: "Classic hoodie with trefoil logo. A staple",
      descriptionRu: "Классическая худи с логотипом трилистника. Маст-хэв",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 41,
      title: "Adidas Crazy Warm hoodie",
      titleRu: "Тёплая худи на молнии Adidas",
      price: "$70",
      imageUrl: "adidas-crazy-warm-hoodie.avif",
      url: "https://www.adidas.com/us/adidas-crazy-warm-fullzip-hoodie/JZ9673.html",
      //TODO: rewrite
      description: "Extra warm full-zip hoodie. For cold days",
      descriptionRu: "Очень тёплая худи на молнии. Для холодных дней",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 42,
      title: "Three 6 Mafia — When The Smoke Clears (Vinyl LP)",
      titleRu: "Three 6 Mafia — When The Smoke Clears (винил)",
      price: "€113",
      imageUrl: "three-6-mafia-wtsc-vinyl.jpg",
      url: "https://www.discogs.com/sell/item/3321466926",
      description: "Memphis legends. Sippin' on Some Syrup",
      descriptionRu: "Легенды Мемфиса. Sippin' on Some Syrup",
      category: "vinyl",
      priority: "medium",
      received: false,
    },
    {
      id: 43,
      title: "Three 6 Mafia — Chpt. 2: World Domination (Vinyl LP)",
      titleRu: "Three 6 Mafia — Chpt. 2: World Domination (винил)",
      price: "£62",
      imageUrl: "three-6-mafia-c2wd-vinyl.jpg",
      url: "https://www.discogs.com/sell/item/2461938065",
      //TODO: rewrite
      description: "The album that started it all. Dark Memphis rap",
      descriptionRu: "Альбом, с которого всё началось. Тёмный мемфисский рэп",
      category: "vinyl",
      priority: "medium",
      received: false,
    },
    {
      id: 44,
      title:
        "Gravediggaz — The Pick, The Sickle And The Shovel (White Vinyl 2xLP)",
      titleRu:
        "Gravediggaz — The Pick, The Sickle And The Shovel (белый винил, 2xLP)",
      price: "$80",
      imageUrl: "gravediggaz-tptats-vinyl.jpg",
      url: "https://www.discogs.com/sell/item/2536779531",
      //TODO: rewrite
      description:
        "RZA's horrorcore supergroup. Second album on 180g white vinyl",
      descriptionRu:
        "Хорроркор-супергруппа RZA. Второй альбом на белом виниле 180г",
      category: "vinyl",
      priority: "low",
      received: false,
      weight: 1,
    },
    {
      id: 45,
      title: "Scentio Milk Plus Shower Cream 2x450ml",
      titleRu: "Крем-гель для душа Scentio Milk Plus 2шт по 450мл",
      price: "$75",
      imageUrl: "scentio-milk-plus-shower-cream.jpg",
      url: "https://www.ebay.com/itm/204688834164",
      //TODO: rewrite
      description: "Thai milk shower cream. Smells amazing, skin feels great",
      descriptionRu:
        "Тайский молочный гель для душа. Пахнет потрясающе, кожа в восторге",
      category: "home",
      priority: "low",
      received: false,
    },
    {
      id: 46,
      title: "Grace & Stella Aloe Vera Gel",
      titleRu: "Гель с алоэ вера Grace & Stella",
      price: "₹2438",
      imageUrl: "grace-stella-aloe-vera-gel.jpg",
      url: "https://kiwla.com/products/grace--stella-aloe-vera-gel",
      description: "Aloe you very much",
      category: "home",
      priority: "low",
      received: false,
    },
    {
      id: 47,
      title: "Salomon X Ultra 5 Mid Gore-Tex",
      titleRu: "Ботинки Salomon X Ultra 5 Mid Gore-Tex",
      price: "$185",
      imageUrl: "salomon-x-ultra-5-mid-gtx.webp",
      url: "https://www.salomon.com/en-us/product/x-ultra-5-mid-gore-tex-li6287/L47754200",
      description: "Another pair of hiking boots",
      descriptionRu: "Ещё одни треккинговые ботинки",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 48,
      title:
        "Georges Perec — Quel petit vélo à guidon chromé au fond de la cour?",
      titleRu:
        "Книга «Что это за маленький мопед с хромированным рулем в глубине двора?», Жорж Перек",
      price: "₽768",
      imageUrl: "perec-moped.jpg",
      url: "https://vse-svobodny.com/product/zhorzh-perek-chto-eto-za-malenkii-moped/",
      //TODO: rewrite
      description: "Perec's early novella. Language games and Algerian war",
      descriptionRu: "Ранняя новелла Перека. Языковые игры и алжирская война",
      category: "books",
      priority: "low",
      received: false,
    },
    {
      id: 49,
      title: "Wolfram Eilenberger — Time of the Magicians",
      titleRu:
        "Книга «Время магов. Великое десятилетие философии», Вольфрам Айленбергер",
      price: "₽672",
      imageUrl: "eilenberger-time-of-magicians.webp",
      url: "https://vse-svobodny.com/product/volfram-ajlenberger-vremya-magov/",
      //TODO: rewrite
      description:
        "Cassirer, Heidegger, Benjamin, Wittgenstein. The 1920s philosophy",
      descriptionRu:
        "Кассирер, Хайдеггер, Беньямин, Витгенштейн. Философия 1920-х",
      category: "books",
      priority: "low",
      received: false,
      weight: 1,
    },
    {
      id: 50,
      title: "Michel Foucault — Discipline and Punish",
      titleRu: "Книга «Надзирать и наказывать. Рождение тюрьмы», Мишель Фуко",
      price: "₽784",
      imageUrl: "foucault-discipline-punish.webp",
      url: "https://vse-svobodny.com/product/fuko-nadzirat-i-nakazyvat-3/",
      //TODO: rewrite
      description: "The birth of the prison. Biopower and surveillance",
      descriptionRu: "Рождение тюрьмы. Биовласть и надзор",
      category: "books",
      priority: "low",
      received: false,
      weight: 3,
    },
    {
      id: 51,
      title: "Michel Foucault — The Birth of the Clinic",
      titleRu:
        "Книга «Рождение клиники. Археология медицинского взгляда», Мишель Фуко",
      price: "₽784",
      imageUrl: "foucault-birth-clinic.jpg",
      url: "https://vse-svobodny.com/product/mishel-fuko-rozhdenie-cliniki/",
      //TODO: rewrite
      description: "Archaeology of medical perception. Early Foucault",
      descriptionRu: "Археология медицинского взгляда. Ранний Фуко",
      category: "books",
      priority: "low",
      received: false,
      weight: 2,
    },
    {
      id: 52,
      title: "Fazer Moomin Soft Fudge (2 pcs)",
      titleRu: "Ириски Fazer Moomin (2 шт)",
      price: "€6.20",
      imageUrl: "fazer-moomin-fudge.webp",
      url: "https://www.fazer.com/en/products/moomin-soft-fudge-candy-bag-160-g-p403386/",
      description: "Tasty Finnish toffees with Moomins",
      descriptionRu: "Вкусные финские ириски с муми-троллями",
      category: "sweets",
      priority: "low",
      received: false,
      weight: 3,
    },
    {
      id: 53,
      title: "Moomin Blueberry-raspberry liquorice stick (30 pcs)",
      titleRu: "Лакричные палочки Fazer Moomin с черникой и малиной (30 шт)",
      price: "€10",
      imageUrl: "moomin-blueberry-raspberry-liquorice-stick.webp",
      url: "https://www.fazer.com/en/products/moomin-blueberry-raspberry-liquorice-stick-20g-p907676/",
      description: "Disgusting liquorice sticks, but with Moomins",
      descriptionRu: "Омерзительные лакричные палочки, но зато с муми-троллями",
      category: "sweets",
      priority: "low",
      received: false,
    },
    {
      id: 54,
      title: "Geisha Seasalt & Caramel chocolate praline",
      titleRu: "Шоколадные конфеты Geisha с морской солью и карамелью",
      price: "€6.50",
      imageUrl: "geisha-caramel-seasalt.webp",
      url: "https://www.fazer.com/en/products/geisha-caramel-sea-salt-100-g-p401720/",
      description: "Very tasty Finnish chocolates",
      descriptionRu: "Очень вкусные финские конфеты",
      category: "sweets",
      priority: "low",
      received: false,
      weight: 2,
    },
    {
      id: 55,
      title: "Fazermint mint chocolate praline",
      titleRu: "Шоколадные конфеты Fazermint с мятой",
      price: "€6.50",
      imageUrl: "fazermint.webp",
      url: "https://www.fazer.com/en/products/fazermint-mint-chocolate-praline-250g-p405315/",
      description: "Finnish dark chocolate candies with mint filling",
      descriptionRu: "Финские конфеты из тёмного шоколада с мятной начинкой",
      category: "sweets",
      priority: "low",
      received: false,
    },
    {
      id: 56,
      title: "Dumle Original (2 pcs)",
      titleRu: "Конфеты Dumle Original (2 шт)",
      price: "€7.80",
      imageUrl: "dumle-original.webp",
      url: "https://www.fazer.com/en/products/dumle-original-200g-p403261/",
      description: "Chocolate-covered toffee candies. Finnish classic",
      descriptionRu: "Классические финские ириски в шоколаде Dumle",
      category: "sweets",
      priority: "low",
      received: false,
      weight: 4,
    },
    {
      id: 57,
      title: "Dumle winter mix candy bag (2 pcs)",
      titleRu: "Конфеты Dumle winter mix (2 шт)",
      price: "€8.60",
      imageUrl: "dumle-winter-mix.webp",
      url: "https://www.fazer.com/en/products/dumle-winter-mix-candy-bag-180g2-p405704/",
      description: "Winter edition Dumle",
      descriptionRu: "Зимний микс Dumle",
      category: "sweets",
      priority: "low",
      received: false,
    },
    {
      id: 58,
      title: "Dumle Mix 295g",
      titleRu: "Конфеты Dumle Mix 295г",
      price: "€3.90",
      imageUrl: "dumle-mix-295g.webp",
      url: "https://www.fazer.com/en/products/dumle-mix-295g-p405340/",
      description: "All Dumle flavors in one bag",
      descriptionRu: "Все вкусы ирисок Dumle в одной упаковке",
      category: "sweets",
      priority: "low",
      received: false,
    },
    {
      id: 59,
      title: "Dumle gift box",
      titleRu: "Подарочная коробка с конфетами Dumle",
      price: "€12.80",
      imageUrl: "dumle-box.webp",
      url: "https://www.fazer.com/en/products/dumle-gift-box-pdumle-box-4084/",
      description: "Mix of Finnish sweets in a gift box",
      descriptionRu: "Микс финских сладостей в подарочной коробке",
      category: "sweets",
      priority: "low",
      received: false,
    },
    {
      id: 60,
      title: "Super Salmiakki 80g (2 pcs)",
      titleRu: "Солёная лакрица Fazer Super Salmiakki 80г (2 шт)",
      price: "€3.40",
      imageUrl: "super-salmiakki.webp",
      url: "https://www.fazer.com/en/products/super-salmiakki-80-g-p403769/",
      description: "Finnish salty liquorice, disgusting",
      descriptionRu: "Финская солёная лакрица, отвратительно",
      category: "sweets",
      priority: "low",
      received: false,
      weight: -2,
    },
    {
      id: 61,
      title: "Remix Salmiakki salty liquorice bag 230g (2 pcs)",
      titleRu: "Ассорти солёной лакрицы Fazer Remix Salmiakki 230г (2 шт)",
      price: "€3.60",
      imageUrl: "fazer-remix-salmiakki.webp",
      url: "https://www.fazer.com/en/products/remix-salmiakki-salty-liquorice-bag-230g-p404191/",
      description: "Finnish salty liquorice, disgusting",
      descriptionRu: "Финская солёная лакрица, отвратительно",
      category: "sweets",
      priority: "low",
      received: false,
      weight: -1,
    },
    {
      id: 62,
      title: "Islanti candies 375g",
      titleRu: "Конфеты Fazer Islanti с белым медведем 375г",
      price: "€7.50",
      imageUrl: "fazer-islanti.webp",
      url: "https://www.fazer.com/en/products/islanti-candies-375g-p403565/",
      description:
        "Polar bear candies. Crunchy shell, soft filling, secret fruit blend",
      descriptionRu:
        "Финские конфеты с белым медведем. Хрустящая оболочка, мягкая начинка, секретный микс фруктов",
      category: "sweets",
      priority: "low",
      received: false,
    },
    {
      id: 63,
      title: "Kiss-kiss 375g",
      titleRu: "Конфеты Fazer Kiss-kiss с котятами 375г",
      price: "€7.50",
      imageUrl: "fazer-kiss-kiss.webp",
      url: "https://www.fazer.com/en/products/kiss-kiss-375g-p403750/",
      description:
        "Finland's oldest candy since 1897. Kittens, pink shell, toffee filling",
      descriptionRu:
        "Старейшие финские конфеты с 1897. Котята, розовая оболочка, ирисковая начинка",
      category: "sweets",
      priority: "low",
      received: false,
    },
    {
      id: 64,
      title: "Daim Chocolates 460g",
      titleRu: "Шоколадные конфеты Daim 460г",
      price: "$30",
      imageUrl: "daim-460g.jpg",
      url: "https://a.co/d/9C9TyEs",
      description: "The best candy in the world",
      descriptionRu: "Вкуснее конфет в жизни не ел",
      category: "sweets",
      priority: "low",
      received: false,
      weight: 1,
    },
    {
      id: 65,
      title: "Krucifix Klan — Fuckin' Wit Dis Klan (Vinyl LP)",
      titleRu: "",
      price: "$58",
      imageUrl: "krucifix-klan-fwdk-vinyl.jpg",
      url: "https://www.discogs.com/sell/item/3742200592",
      description: "",
      descriptionRu: "",
      category: "vinyl",
      priority: "low",
      received: false,
    },
    {
      id: 66,
      title: "Koopsta Knicca — Da Devil's Playground (Vinyl LP)",
      titleRu: "",
      price: "$65",
      imageUrl: "koopsta-knicca-ddp-vinyl.jpg",
      url: "https://www.discogs.com/sell/item/3964651738",
      description: "",
      descriptionRu: "",
      category: "vinyl",
      priority: "low",
      received: false,
    },
  ]);

  // Seed reservations for testing
  await db.insert(Reservation).values([
    {
      id: 1,
      itemId: 12, // Hollow Knight Blanket
      reservedBy: "test-visitor",
      reservedAt: new Date(),
      reservationToken: randomUUID(),
      status: "confirmed",
    },
    {
      id: 2,
      itemId: 53, // Moomin Blueberry-raspberry liquorice stick
      reservedBy: "test-visitor",
      reservedAt: new Date(),
      reservationToken: randomUUID(),
      status: "confirmed",
    },
    {
      id: 3,
      itemId: 56, // Dumle Original
      reservedBy: "test-visitor",
      reservedAt: new Date(),
      reservationToken: randomUUID(),
      status: "confirmed",
    },
    {
      id: 4,
      itemId: 58, // Dumle Mix 295g
      reservedBy: "test-visitor",
      reservedAt: new Date(),
      reservationToken: randomUUID(),
      status: "confirmed",
    },
  ]);
}
