import { db, WishlistItem, ExchangeRate } from "astro:db";
import { CDN_DEV_URL } from "astro:env/server";

const img = (name: string) => `${CDN_DEV_URL}/${name}`;

// https://astro.build/db/seed
export default async function seed() {
  // Insert exchange rates (to RUB)
  await db.insert(ExchangeRate).values([
    {
      id: 1,
      fromCurrency: "USD",
      toCurrency: "RUB",
      rate: 82,
      updatedAt: new Date(),
    },
    {
      id: 2,
      fromCurrency: "EUR",
      toCurrency: "RUB",
      rate: 98,
      updatedAt: new Date(),
    },
    {
      id: 3,
      fromCurrency: "GBP",
      toCurrency: "RUB",
      rate: 112,
      updatedAt: new Date(),
    },
    {
      id: 4,
      fromCurrency: "AUD",
      toCurrency: "RUB",
      rate: 56,
      updatedAt: new Date(),
    },
  ]);

  await db.insert(WishlistItem).values([
    {
      id: 1,
      title: "The Florida Project Limited Edition 4K UHD",
      titleRu: "Проект Флорида 4K UHD, лимитированное издание",
      price: "$64",
      imageUrl: img("second-sight-florida-project.webp"),
      description: "",
      descriptionRu: "",
      url: "https://www.ebay.com/itm/306576066529",
      category: "blu-ray",
      priority: "medium",
      received: false,
    },
    {
      id: 2,
      title: "Tangerine Limited Edition Blu-ray",
      titleRu: "Мандарин на Blu-ray, лимитированное издание",
      price: "£25",
      imageUrl: img("second-sight-tangerine.webp"),
      description: "",
      descriptionRu: "",
      url: "https://secondsightfilms.co.uk/products/tangerine-limited-edition-blu-ray-pre-order-available-december-19th",
      category: "blu-ray",
      priority: "medium",
      received: false,
    },
    {
      id: 5,
      title: "Titanium Band for Apple Watch Ultra",
      titleRu: "Титановый ремешок для Apple Watch Ultra",
      price: "$249",
      imageUrl: img("apple-watch-band.webp"),
      url: "https://nomadgoods.com/products/titanium-band-46mm-49mm-natural-hardware-v3",
      description: "A band to pretend I’m not broke",
      descriptionRu: "Ремешок, чтобы притворяться, что я не броук",
      category: "other",
      priority: "low",
      received: false,
    },
    {
      id: 6,
      title: "Astro Bot Soundtrack Vinyl",
      titleRu: "Саундтрек Astro Bot на виниле",
      price: "$39",
      imageUrl: img("astrobot-vinyl.webp"),
      url: "https://www.fangamer.com/collections/astro-bot/products/astro-bot-2024-vinyl",
      description: "",
      descriptionRu: "Роботик, роботик, роботик",
      category: "vinyl",
      priority: "low",
      received: false,
    },
    {
      id: 7,
      title: "Celeste Desk Mat",
      titleRu: "Коврик для стола Celeste",
      price: "$28",

      imageUrl: img("celeste-deskmat.webp"),
      url: "https://www.fangamer.com/collections/celeste/products/celeste-desk-mat-skies",
      description: "Large desk mat with Celeste artwork",
      descriptionRu: "Большой коврик для стола с артом из Celeste",
      category: "merch,home",
      priority: null,
      received: true,
    },
    {
      id: 8,
      title: "TPOB XO Clipper (Slime Edition)",
      titleRu: "Машинка для стрижки TPOB XO (Slime)",
      price: "$74",

      imageUrl: img("tpob-xo-clipper.webp"),
      url: "https://tpobusa.com/collections/clippers/products/xo-clipper-slime",
      description:
        "Professional cordless clipper so I can cut my hair at home and avoid people",
      descriptionRu:
        "Профессиональная беспроводная машинка для стрижки своей головы дома, чтобы избегать людей",
      category: "home",
      priority: "high",
      received: false,
    },
    {
      id: 9,
      title: "TPOB Mini Skull (Blackout edition)",
      titleRu: "Электробритва TPOB Mini Skull (Blackout)",
      price: "$45",

      imageUrl: img("tpob-mini-skull.webp"),
      url: "https://tpobusa.com/collections/shavers/products/blackout-mini-skull",
      description: "Compact electric shaver for travel",
      descriptionRu: "Компактная электробритва в дорогу",
      category: "home",
      priority: "high",
      received: false,
    },
    {
      id: 10,
      title: "Hollow Knight Gods & Nightmares Vinyl Soundtrack",
      titleRu: "Саундтрек Hollow Knight: Gods & Nightmares на виниле",
      price: "$29",

      imageUrl: img("hollowknight-vinyl.webp"),
      url: "https://www.fangamer.com/collections/vinyl-game-soundtracks/products/hollow-knight-gods-nightmares-vinyl-soundtrack",
      description: "",
      descriptionRu: "",
      category: "vinyl",
      priority: "low",
      received: false,
    },
    {
      id: 11,
      title:
        "Hollow Knight Collector's Edition for Nintendo Switch + Wanderer's Journal",
      titleRu:
        "Коллекционное издание Hollow Knight для Nintendo Switch + Журнал Охотника",
      price: "$107",

      imageUrl: img("hollowknight-collectors-edition.webp"),
      url: "https://www.fangamer.com/products/hollow-knight-game-collectors-edition-nintendo-switch",
      description: "",
      descriptionRu: "",
      category: "merch",
      priority: "low",
      received: false,
    },
    {
      id: 12,
      title: "Hollow Knight Blanket",
      titleRu: "Плед Hollow Knight",
      price: "$45",

      imageUrl: img("hollowknight-blanket.webp"),
      url: "https://www.fangamer.com/products/hollow-knight-blanket",
      description: "A blanket to wrap myself in instead of dealing with life",
      descriptionRu:
        "Плед, чтобы завернуться в него вместо того, чтобы разбираться с жизнью",
      category: "merch,home",
      priority: "medium",
      received: false,
    },
    {
      id: 13,
      title: "X Trilogy: Collector's Edition Box Set (4K UHD)",
      titleRu: "Трилогия X: Коллекционное издание (4K UHD)",
      price: "$100",

      imageUrl: img("a24-x-trilogy.webp"),
      url: "https://shop.a24films.com/products/x-trilogy-collectors-edition",
      description:
        "3-disc box set with X, Pearl, MaXXXine — packaging is indecently beautiful",
      descriptionRu:
        "Бокс-сет из 3 дисков с X, Pearl, MaXXXine — упаковка неприлично красивая",
      category: "blu-ray",
      priority: "medium",
      received: false,
    },
    {
      id: 14,
      title: "Possession 4K Limited Edition UHD Blu-ray",
      titleRu: "Одержимая 4K UHD, лимитированное издание",
      price: "$85",

      imageUrl: img("second-sight-possesion.webp"),
      url: "https://www.ebay.com/itm/326922568960",
      description: "",
      descriptionRu: "",
      category: "blu-ray",
      priority: "medium",
      received: false,
    },
    {
      id: 15,
      title: "The Straight Story Blu-ray",
      titleRu: "Простая история на Blu-ray",
      price: "AU$140",

      imageUrl: img("imprint-the-straight-story.webp"),
      url: "https://www.ebay.com/itm/276396157419",
      description:
        "David Lynch, but calm. A straight story. The only Lynch film I don't have in my collection yet",
      descriptionRu:
        "Дэвид Линч, но спокойный и простой. Единственный его фильм которого у меня еще нет в коллекции",
      category: "blu-ray",
      priority: "medium",
      received: false,
    },
    {
      id: 16,
      title: "Tokyo Decadence Blu-ray",
      titleRu: "Токийский декаданс на Blu-ray",
      price: "$31",

      imageUrl: img("tokyo-decadence.webp"),
      url: "https://www.ebay.com/itm/375499327864",
      description: "",
      descriptionRu: "",
      category: "blu-ray",
      priority: "low",
      received: false,
    },
    {
      id: 17,
      title: "555 Soundtrack Vinyl LP",
      titleRu: "Саундтрек 555 на виниле, очень редкий",
      price: "$57",

      imageUrl: img("555-vinyl.webp"),
      url: "https://www.ebay.com/itm/176437398555",
      description: "Limited to 50 copies. Unfortunately, I need this",
      descriptionRu: "Лимитированное издание, тираж 50 копий. Это мне надо.",
      category: "vinyl",
      priority: "medium",
      received: false,
    },
    {
      id: 18,
      title: "Nekromantik Soundtrack Vinyl LP + EP",
      titleRu: "Саундтрек Некромантик на виниле, очень редкий",
      price: "€300",

      imageUrl: img("nekromantik-vinyl.webp"),
      url: "https://www.ebay.com/itm/134673382645",
      description:
        "Absurdly rare and absurdly expensive. Unfortunately, I need this",
      descriptionRu:
        "Нелепо редкий и нелепо дорогой. К сожалению, это мне нужно",
      category: "vinyl",
      priority: "medium",
      received: false,
    },
    {
      id: 19,
      title: "Nekromantik T-Shirt",
      titleRu: "Футболка Nekromantik",
      price: "$25",

      imageUrl: img("nekromantik-tshirt.webp"),
      url: "https://www.ebay.com/itm/135116828682",
      description: "",
      descriptionRu: "",
      category: "merch,clothing",
      priority: "medium",
      received: false,
    },
    {
      id: 20,
      title: "Vans Sk8-Hi",
      titleRu: "Vans Sk8-Hi",
      price: "$145",

      imageUrl: img("vans-sk8hi.avif"),
      url: "https://www.vans.com/en-us/p/shoes/icons/sk8-hi-5325/sk8-hi-waterproof-insulated-shoe-VN000DAQBKA?size=8.5+Men+%3D+10.0+Women",
      description: "Waterproof and insulated — for winter",
      descriptionRu: "С водозащитой и утеплением — на зиму",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 21,
      title: "Jordan Club Hat",
      titleRu: "Кепка Jordan Club",
      price: "$25",

      imageUrl: img("jordan-club-hat.avif"),
      url: "https://www.nike.com/t/jordan-club-unstructured-curved-bill-hat-TR8rQt/HQ1963-010",
      description: "Simple black cap",
      descriptionRu: "Простая чёрная кепка",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 22,
      title: "Philips Sonicare 9900 Prestige",
      titleRu: "Электрическая зубная щётка Philips Sonicare 9900 Prestige",
      price: "$300",

      imageUrl: img("philips-sonicare-diamondclean.webp"),
      url: "https://a.co/d/49pcu6S",
      description: "",
      descriptionRu: "",
      category: "home",
      priority: "high",
      received: false,
    },
    {
      id: 23,
      title: "Yung Lean — Warlord (White Vinyl LP)",
      titleRu: "Yung Lean — Warlord (белый винил, лимитированное издание)",
      price: "$70",

      imageUrl: img("yung-lean-warlord-vinyl.webp"),
      url: "https://www.discogs.com/sell/item/1950442079",
      description: "My favorite Yung Lean album. Pure 2016 nostalgia",
      descriptionRu: "Мой любимый альбом Yung Lean, ностальгия по 2016",
      category: "vinyl",
      priority: "medium",
      received: false,
    },
    {
      id: 24,
      title: "Funko POP Twin Peaks Laura Palmer",
      titleRu: "Funko POP Twin Peaks (Лора Палмер)",
      price: "$120",

      imageUrl: img("funko-pop-laura-palmer.jpg"),
      url: "https://a.co/d/fqFZyLg",
      description: "Extremely rare. And yes, that’s the whole reason.",
      descriptionRu: "Крайне редкая",
      category: "merch,other",
      priority: "medium",
      received: false,
    },
    {
      id: 25,
      title: "Boy Harsher — Lesser Man EP (Red Translucent Vinyl)",
      titleRu:
        "Boy Harsher — Lesser Man EP (красный винил, лимитированное издание)",
      price: "€50",

      imageUrl: img("boy-harsher-lesser-man-vinyl.jpg"),
      url: "https://www.discogs.com/sell/item/2961810748",
      description: "",
      descriptionRu: "",
      category: "vinyl",
      priority: "medium",
      received: false,
    },
    {
      id: 26,
      title: "Philips Sonicare Power Flosser 3000",
      titleRu: "Ирригатор Philips Sonicare Power Flosser 3000",
      price: "$70",

      imageUrl: img("philips-sonicare-flosser.jpg"),
      url: "https://a.co/d/hrfsFUQ",
      description: "",
      descriptionRu: "",
      category: "home",
      priority: "high",
      received: false,
    },
    {
      id: 27,
      title: "Adidas Terrex Free Hiker 2.0 Low GORE-TEX",
      price: "$180",

      imageUrl: img("terrex-shoes.avif"),
      url: "https://www.adidas.com/us/terrex-free-hiker-2.0-low-gore-tex-hiking-shoes/IH0672.html?forceSelSize=9",
      description: "I need sneakers for city, hiking, and shitty weather",
      descriptionRu:
        "Нужны кроссы и для города, и для хайкинга, и для всратой погоды",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 28,
      title: "Adidas Beanie",
      titleRu: "Шапка Adidas",
      price: "$17",

      imageUrl: img("adidas-beanie.avif"),
      url: "https://www.adidas.com/us/unisex-trefoil-beanie/JL1081.html",
      description: "Basic beanie",
      descriptionRu: "Базовая шапка",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 29,
      title: "RIPNDIP Boxers 3 Pack",
      titleRu: "Боксеры RIPNDIP 3 шт.",
      price: "$36",

      imageUrl: img("ripndip-boxers.webp"),
      url: "https://www.ripndipclothing.com/en-kz/collections/holiday-2025/products/smd-boxers-3-pack-multi",
      description: "",
      descriptionRu: "",
      category: "clothing",
      priority: "medium",
      received: false,
    },
    {
      id: 30,
      title: "RIPNDIP Longsleeve",
      titleRu: "Лонгслив RIPNDIP",
      price: "$44",

      imageUrl: img("ripndip-long-sleave.webp"),
      url: "https://www.ripndipclothing.com/collections/holiday-2025/products/the-happiest-cat-ls-black",
      description: "",
      descriptionRu: "",
      category: "clothing",
      priority: "medium",
      received: false,
    },
    {
      id: 31,
      title: "RIPNDIP Knit Sweater",
      titleRu: "Свитер RIPNDIP",
      price: "$80",

      imageUrl: img("ripndip-knit-sweater.webp"),
      url: "https://www.ripndipclothing.com/collections/holiday-2025/products/out-of-this-world-knit-sweater-black",
      description: "",
      descriptionRu: "",
      category: "clothing",
      priority: "medium",
      received: false,
    },
    {
      id: 32,
      title: "Vans Skate Half Cab",
      price: "$85",

      imageUrl: img("vans-skate-half-cab.avif"),
      url: "https://www.vans.com/en-us/p/shoes/icons/half-cab-1992/skate-half-cab-shoe-VN0A5FCDY28?size=8.5+Men+=+10.0+Women",
      description: "",
      descriptionRu: "",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 33,
      title: "Philips Norelco Head Shaver Pro 7000 Series",
      titleRu: "",
      price: "$85",
      imageUrl: img("philips-head-shaver.webp"),
      url: "https://www.usa.philips.com/c-p/HS7980_40/head-shaver-pro-7000-series-advanced-shaver-with-90-min-runt~",
      description: "",
      descriptionRu: "",
      category: "home",
      priority: "high",
      received: false,
    },
    {
      id: 34,
      title: "Cotton Classics 3-Pack Classic Fit Crewneck T-Shirt",
      titleRu: "",
      price: "$37",
      imageUrl: img("ck-3-pack-t-shirt.webp"),
      url: "https://www.calvinklein.us/en/underwear/men/undershirt-tank/cotton-classics-3-pack-classic-fit-crewneck-t-shirt/NB4051-UB1.html",
      description: "",
      descriptionRu: "",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 35,
      title: "Tech Pique T-Shirt",
      titleRu: "",
      price: "$35",
      imageUrl: img("ck-tech-pique-t-shirt.webp"),
      url: "https://www.calvinklein.us/en/men/apparel/tops/tech-pique-t-shirt/4LD298G-UB1.html",
      description: "",
      descriptionRu: "",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 36,
      title: "Trefoil Essentials Oversized Tee",
      titleRu: "",
      price: "$24",
      imageUrl: img("adidas-oversized-tee.avif"),
      url: "https://www.adidas.com/us/trefoil-essentials-oversized-tee/JD0349.html",
      description: "",
      descriptionRu: "",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 37,
      title: "Trefoil Essentials Pants",
      titleRu: "",
      price: "$48",
      imageUrl: img("adidas-pants.avif"),
      url: "https://www.adidas.com/us/trefoil-essentials-pants/IY7361.html?forceSelSize=XS",
      description: "",
      descriptionRu: "",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 38,
      title: "Essentials 3-Stripes Fleece Pants",
      titleRu: "",
      price: "$50",
      imageUrl: img("adidas-3-stripes-pants.avif"),
      url: "https://www.adidas.com/us/essentials-3-stripes-fleece-pants/KE7273.html?forceSelSize=XS",
      description: "",
      descriptionRu: "",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 39,
      title: "SOFT LUX SWEATSHIRT",
      titleRu: "",
      price: "$50",
      imageUrl: img("adidas-sweatshirt.avif"),
      url: "https://www.adidas.com/us/soft-lux-sweatshirt/KF0485.html?pr=pdpctl_rr&slot=3&rec=ds&forceSelSize=S",
      description: "",
      descriptionRu: "",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 40,
      title: "Trefoil Essentials Hoodie",
      titleRu: "",
      price: "$36",
      imageUrl: img("adidas-hoodie.avif"),
      url: "https://www.adidas.com/us/trefoil-essentials-hoodie/IY4930.html",
      description: "",
      descriptionRu: "",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 41,
      title: "ADIDAS CRAZY WARM FULLZIP HOODIE",
      titleRu: "",
      price: "$70",
      imageUrl: img("adidas-crazy-warm-hoodie.avif"),
      url: "https://www.adidas.com/us/adidas-crazy-warm-fullzip-hoodie/JZ9673.html",
      description: "",
      descriptionRu: "",
      category: "clothing",
      priority: "high",
      received: false,
    },
    {
      id: 42,
      title: "Three 6 Mafia — When The Smoke Clears (Vinyl LP)",
      titleRu: "Three 6 Mafia — When The Smoke Clears (винил)",
      price: "€113",
      imageUrl: img("three-6-mafia-wtsc-vinyl.jpg"),
      url: "https://www.discogs.com/sell/item/3321466926",
      description: "",
      descriptionRu: "",
      category: "vinyl",
      priority: "medium",
      received: false,
    },
    {
      id: 43,
      title: "Three 6 Mafia — Chpt. 2: World Domination (Vinyl LP)",
      titleRu: "Three 6 Mafia — Chpt. 2: World Domination (винил)",
      price: "£62",
      imageUrl: img("three-6-mafia-c2wd-vinyl.jpg"),
      url: "https://www.discogs.com/sell/item/2461938065",
      description: "",
      descriptionRu: "",
      category: "vinyl",
      priority: "medium",
      received: false,
    },
  ]);
}
