import * as countryList from "../../pages/travel/countries.md";
import { countries as visitedCountryCodes } from "./index";
import { getByCode } from "./countries";

export type CategoryId =
  | "member-states"
  | "observer-states"
  | "dependent-territories"
  | "partially-recognized";

export interface ChecklistCategory {
  id: CategoryId;
  name: string;
  nameRu: string;
  countries: ChecklistCountry[];
}

export interface ChecklistCountry {
  name: string;
  nameShort: string;
  nameShortRu: string;
  a2: string;
  visited: boolean;
}

interface ParsedSection {
  id: CategoryId;
  name: string;
  nameRu: string;
  countries: string[];
}

// Short names for common long country names
const SHORT_NAMES: Record<string, string> = {
  "Islamic Republic of Afghanistan": "Afghanistan",
  "Republic of Albania": "Albania",
  "People’s Democratic Republic of Algeria": "Algeria",
  "Principality of Andorra": "Andorra",
  "Republic of Angola": "Angola",
  "Republic of Argentina": "Argentina",
  "Republic of Armenia": "Armenia",
  "Commonwealth of Australia": "Australia",
  "Republic of Austria": "Austria",
  "Republic of Azerbaijan": "Azerbaijan",
  "Commonwealth of the Bahamas": "Bahamas",
  "Kingdom of Bahrain": "Bahrain",
  "People’s Republic of Bangladesh": "Bangladesh",
  "Republic of Belarus": "Belarus",
  "Kingdom of Belgium": "Belgium",
  "Republic of Benin": "Benin",
  "Kingdom of Bhutan": "Bhutan",
  "Plurinational State of Bolivia (Plurinational State of)": "Bolivia",
  "Republic of Botswana": "Botswana",
  "Federative Republic of Brazil": "Brazil",
  "Negara Brunei Darussalam": "Brunei",
  "Republic of Bulgaria": "Bulgaria",
  "Republic of Burundi": "Burundi",
  "Kingdom of Cambodia": "Cambodia",
  "Republic of Cameroon": "Cameroon",
  "Republic of Cabo Verde": "Cabo Verde",
  "Republic of Chad": "Chad",
  "Republic of Chile": "Chile",
  "People’s Republic of China": "China",
  "Republic of Colombia": "Colombia",
  "Union of the Comoros": "Comoros",
  "Republic of the Congo": "Congo",
  "Republic of Costa Rica": "Costa Rica",
  "Republic of Côte d’Ivoire": "Côte d’Ivoire",
  "Republic of Croatia": "Croatia",
  "Republic of Cuba": "Cuba",
  "Republic of Cyprus": "Cyprus",
  "Czech Republic (Czechia)": "Czechia",
  "Democratic People’s Republic of Korea": "North Korea",
  "Democratic Republic of the Congo": "DR Congo",
  "Kingdom of Denmark": "Denmark",
  "Republic of Djibouti": "Djibouti",
  "Commonwealth of Dominica": "Dominica",
  "Republic of Ecuador": "Ecuador",
  "Arab Republic of Egypt": "Egypt",
  "Republic of El Salvador": "El Salvador",
  "Republic of Equatorial Guinea": "Equatorial Guinea",
  "State of Eritrea": "Eritrea",
  "Republic of Estonia": "Estonia",
  "Kingdom of Eswatini": "Eswatini",
  "Federal Democratic Republic of Ethiopia": "Ethiopia",
  "Republic of Fiji": "Fiji",
  "Republic of Finland": "Finland",
  "Republic of France": "France",
  "Gabonese Republic (Gabon)": "Gabon",
  "Republic of The Gambia": "Gambia",
  "Federal Republic of Germany": "Germany",
  "Republic of Ghana": "Ghana",
  "Hellenic Republic (Greece)": "Greece",
  "Republic of Guatemala": "Guatemala",
  "Republic of Guinea": "Guinea",
  "Republic of Guinea-Bissau": "Guinea-Bissau",
  "Co-operative Republic of Guyana": "Guyana",
  "Republic of Haiti": "Haiti",
  "Republic of Honduras": "Honduras",
  "Republic of India": "India",
  "Republic of Indonesia": "Indonesia",
  "Islamic Republic of Iran (Islamic Republic of)": "Iran",
  "Republic of Iraq": "Iraq",
  "State of Israel": "Israel",
  "Republic of Italy": "Italy",
  "Hashemite Kingdom of Jordan": "Jordan",
  "Republic of Kazakhstan": "Kazakhstan",
  "Republic of Kenya": "Kenya",
  "Republic of Kiribati": "Kiribati",
  "State of Kuwait": "Kuwait",
  "Kyrgyz Republic (Kyrgyzstan)": "Kyrgyzstan",
  "Lao People’s Democratic Republic": "Laos",
  "Republic of Latvia": "Latvia",
  "Republic of Lebanon": "Lebanon",
  "Kingdom of Lesotho": "Lesotho",
  "Republic of Liberia": "Liberia",
  "State of Libya": "Libya",
  "Principality of Liechtenstein": "Liechtenstein",
  "Republic of Lithuania": "Lithuania",
  "Grand Duchy of Luxembourg": "Luxembourg",
  "Republic of Madagascar": "Madagascar",
  "Republic of Malawi": "Malawi",
  "Republic of Maldives": "Maldives",
  "Republic of Mali": "Mali",
  "Republic of Malta": "Malta",
  "Republic of the Marshall Islands": "Marshall Islands",
  "Islamic Republic of Mauritania": "Mauritania",
  "Republic of Mauritius": "Mauritius",
  "United Mexican States (Mexico)": "Mexico",
  "Federated States of Micronesia (Federated States of)": "Micronesia",
  "Principality of Monaco": "Monaco",
  "Kingdom of Morocco": "Morocco",
  "Republic of Mozambique": "Mozambique",
  "Republic of the Union of Myanmar": "Myanmar",
  "Republic of Namibia": "Namibia",
  "Republic of Nauru": "Nauru",
  "Kingdom of the Netherlands (Kingdom of the)": "Netherlands",
  "Republic of Nicaragua": "Nicaragua",
  "Republic of the Niger": "Niger",
  "Federal Republic of Nigeria": "Nigeria",
  "Republic of North Macedonia": "North Macedonia",
  "Kingdom of Norway": "Norway",
  "Sultanate of Oman": "Oman",
  "Islamic Republic of Pakistan": "Pakistan",
  "Republic of Palau": "Palau",
  "Republic of Panama": "Panama",
  "Independent State of Papua New Guinea": "Papua New Guinea",
  "Republic of Paraguay": "Paraguay",
  "Republic of Peru": "Peru",
  "Republic of the Philippines": "Philippines",
  "Republic of Poland": "Poland",
  "Portuguese Republic (Portugal)": "Portugal",
  "State of Qatar": "Qatar",
  "Republic of Korea": "South Korea",
  "Republic of Moldova": "Moldova",
  "Russian Federation": "Russia",
  "Republic of Rwanda": "Rwanda",
  "Republic of San Marino": "San Marino",
  "Democratic Republic of Sao Tome and Principe": "São Tomé and Príncipe",
  "Kingdom of Saudi Arabia": "Saudi Arabia",
  "Republic of Senegal": "Senegal",
  "Republic of Serbia": "Serbia",
  "Republic of Seychelles": "Seychelles",
  "Republic of Sierra Leone": "Sierra Leone",
  "Republic of Singapore": "Singapore",
  "Slovak Republic (Slovakia)": "Slovakia",
  "Republic of Slovenia": "Slovenia",
  "Federal Republic of Somalia": "Somalia",
  "Republic of South Africa": "South Africa",
  "Republic of South Sudan": "South Sudan",
  "Kingdom of Spain": "Spain",
  "Democratic Socialist Republic of Sri Lanka": "Sri Lanka",
  "Republic of the Sudan": "Sudan",
  "Republic of Suriname": "Suriname",
  "Kingdom of Sweden": "Sweden",
  "Swiss Confederation (Switzerland)": "Switzerland",
  "Syrian Arab Republic": "Syria",
  "Republic of Tajikistan": "Tajikistan",
  "Kingdom of Thailand": "Thailand",
  "Democratic Republic of Timor-Leste": "Timor-Leste",
  "Republic of Togo": "Togo",
  "Kingdom of Tonga": "Tonga",
  "Republic of Trinidad and Tobago": "Trinidad and Tobago",
  "Republic of Tunisia": "Tunisia",
  "Republic of Türkiye": "Türkiye",
  "Republic of Uganda": "Uganda",
  "United Arab Emirates": "UAE",
  "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
  "United Republic of Tanzania": "Tanzania",
  "United States of America": "United States",
  "Oriental Republic of Uruguay": "Uruguay",
  "Republic of Uzbekistan": "Uzbekistan",
  "Republic of Vanuatu": "Vanuatu",
  "Bolivarian Republic of Venezuela": "Venezuela",
  "Socialist Republic of Viet Nam": "Vietnam",
  "Republic of Yemen": "Yemen",
  "Republic of Zambia": "Zambia",
  "Republic of Zimbabwe": "Zimbabwe",
  "State of Palestine": "Palestine",
  "Holy See": "Vatican",
  "Hong Kong SAR": "Hong Kong",
  "Macao SAR": "Macao",
  "Republic of Abkhazia": "Abkhazia",
  "Republic of China (Taiwan)": "Taiwan",
  "Republic of Kosovo": "Kosovo",
  "Turkish Republic of Northern Cyprus": "Northern Cyprus",
  "Pridnestrovian Moldovan Republic (Transnistria)": "Transnistria",
  "Sahrawi Arab Democratic Republic (Western Sahara)": "Western Sahara",
  "Republic of Somaliland": "Somaliland",
  "Republic of South Ossetia (State of Alania)": "South Ossetia",
};

// Map official names to ISO 3166-1 alpha-2 codes
const NAME_TO_A2: Record<string, string> = {
  "Islamic Republic of Afghanistan": "af",
  "Republic of Albania": "al",
  "People’s Democratic Republic of Algeria": "dz",
  "Principality of Andorra": "ad",
  "Republic of Angola": "ao",
  "Antigua and Barbuda": "ag",
  "Republic of Argentina": "ar",
  "Republic of Armenia": "am",
  "Commonwealth of Australia": "au",
  "Republic of Austria": "at",
  "Republic of Azerbaijan": "az",
  "Commonwealth of the Bahamas": "bs",
  "Kingdom of Bahrain": "bh",
  "People’s Republic of Bangladesh": "bd",
  Barbados: "bb",
  "Republic of Belarus": "by",
  "Kingdom of Belgium": "be",
  Belize: "bz",
  "Republic of Benin": "bj",
  "Kingdom of Bhutan": "bt",
  "Plurinational State of Bolivia (Plurinational State of)": "bo",
  "Bosnia and Herzegovina": "ba",
  "Republic of Botswana": "bw",
  "Federative Republic of Brazil": "br",
  "Negara Brunei Darussalam": "bn",
  "Republic of Bulgaria": "bg",
  "Burkina Faso": "bf",
  "Republic of Burundi": "bi",
  "Kingdom of Cambodia": "kh",
  "Republic of Cameroon": "cm",
  Canada: "ca",
  "Republic of Cabo Verde": "cv",
  "Central African Republic": "cf",
  "Republic of Chad": "td",
  "Republic of Chile": "cl",
  "People’s Republic of China": "cn",
  "Republic of Colombia": "co",
  "Union of the Comoros": "km",
  "Republic of the Congo": "cg",
  "Republic of Costa Rica": "cr",
  "Republic of Côte d’Ivoire": "ci",
  "Republic of Croatia": "hr",
  "Republic of Cuba": "cu",
  "Republic of Cyprus": "cy",
  "Czech Republic (Czechia)": "cz",
  "Democratic People’s Republic of Korea": "kp",
  "Democratic Republic of the Congo": "cd",
  "Kingdom of Denmark": "dk",
  "Republic of Djibouti": "dj",
  "Commonwealth of Dominica": "dm",
  "Dominican Republic": "do",
  "Republic of Ecuador": "ec",
  "Arab Republic of Egypt": "eg",
  "Republic of El Salvador": "sv",
  "Republic of Equatorial Guinea": "gq",
  "State of Eritrea": "er",
  "Republic of Estonia": "ee",
  "Kingdom of Eswatini": "sz",
  "Federal Democratic Republic of Ethiopia": "et",
  "Republic of Fiji": "fj",
  "Republic of Finland": "fi",
  "Republic of France": "fr",
  "Gabonese Republic (Gabon)": "ga",
  "Republic of The Gambia": "gm",
  Georgia: "ge",
  "Federal Republic of Germany": "de",
  "Republic of Ghana": "gh",
  "Hellenic Republic (Greece)": "gr",
  Grenada: "gd",
  "Republic of Guatemala": "gt",
  "Republic of Guinea": "gn",
  "Republic of Guinea-Bissau": "gw",
  "Co-operative Republic of Guyana": "gy",
  "Republic of Haiti": "ht",
  "Republic of Honduras": "hn",
  Hungary: "hu",
  Iceland: "is",
  "Republic of India": "in",
  "Republic of Indonesia": "id",
  "Islamic Republic of Iran (Islamic Republic of)": "ir",
  "Republic of Iraq": "iq",
  Ireland: "ie",
  "State of Israel": "il",
  "Republic of Italy": "it",
  Jamaica: "jm",
  Japan: "jp",
  "Hashemite Kingdom of Jordan": "jo",
  "Republic of Kazakhstan": "kz",
  "Republic of Kenya": "ke",
  "Republic of Kiribati": "ki",
  "State of Kuwait": "kw",
  "Kyrgyz Republic (Kyrgyzstan)": "kg",
  "Lao People’s Democratic Republic": "la",
  "Republic of Latvia": "lv",
  "Republic of Lebanon": "lb",
  "Kingdom of Lesotho": "ls",
  "Republic of Liberia": "lr",
  "State of Libya": "ly",
  "Principality of Liechtenstein": "li",
  "Republic of Lithuania": "lt",
  "Grand Duchy of Luxembourg": "lu",
  "Republic of Madagascar": "mg",
  "Republic of Malawi": "mw",
  Malaysia: "my",
  "Republic of Maldives": "mv",
  "Republic of Mali": "ml",
  "Republic of Malta": "mt",
  "Republic of the Marshall Islands": "mh",
  "Islamic Republic of Mauritania": "mr",
  "Republic of Mauritius": "mu",
  "United Mexican States (Mexico)": "mx",
  "Federated States of Micronesia (Federated States of)": "fm",
  "Principality of Monaco": "mc",
  Mongolia: "mn",
  Montenegro: "me",
  "Kingdom of Morocco": "ma",
  "Republic of Mozambique": "mz",
  "Republic of the Union of Myanmar": "mm",
  "Republic of Namibia": "na",
  "Republic of Nauru": "nr",
  Nepal: "np",
  "Kingdom of the Netherlands (Kingdom of the)": "nl",
  "New Zealand": "nz",
  "Republic of Nicaragua": "ni",
  "Republic of the Niger": "ne",
  "Federal Republic of Nigeria": "ng",
  "Republic of North Macedonia": "mk",
  "Kingdom of Norway": "no",
  "Sultanate of Oman": "om",
  "Islamic Republic of Pakistan": "pk",
  "Republic of Palau": "pw",
  "Republic of Panama": "pa",
  "Independent State of Papua New Guinea": "pg",
  "Republic of Paraguay": "py",
  "Republic of Peru": "pe",
  "Republic of the Philippines": "ph",
  "Republic of Poland": "pl",
  "Portuguese Republic (Portugal)": "pt",
  "State of Qatar": "qa",
  "Republic of Korea": "kr",
  "Republic of Moldova": "md",
  Romania: "ro",
  "Russian Federation": "ru",
  "Republic of Rwanda": "rw",
  "Saint Kitts and Nevis": "kn",
  "Saint Lucia": "lc",
  "Saint Vincent and the Grenadines": "vc",
  "Independent State of Samoa": "ws",
  "Republic of San Marino": "sm",
  "Democratic Republic of Sao Tome and Principe": "st",
  "Kingdom of Saudi Arabia": "sa",
  "Republic of Senegal": "sn",
  "Republic of Serbia": "rs",
  "Republic of Seychelles": "sc",
  "Republic of Sierra Leone": "sl",
  "Republic of Singapore": "sg",
  "Slovak Republic (Slovakia)": "sk",
  "Republic of Slovenia": "si",
  "Solomon Islands": "sb",
  "Federal Republic of Somalia": "so",
  "Republic of South Africa": "za",
  "Republic of South Sudan": "ss",
  "Kingdom of Spain": "es",
  "Democratic Socialist Republic of Sri Lanka": "lk",
  "Republic of the Sudan": "sd",
  "Republic of Suriname": "sr",
  "Kingdom of Sweden": "se",
  "Swiss Confederation (Switzerland)": "ch",
  "Syrian Arab Republic": "sy",
  "Republic of Tajikistan": "tj",
  "Kingdom of Thailand": "th",
  "Democratic Republic of Timor-Leste": "tl",
  "Republic of Togo": "tg",
  "Kingdom of Tonga": "to",
  "Republic of Trinidad and Tobago": "tt",
  "Republic of Tunisia": "tn",
  "Republic of Türkiye": "tr",
  Turkmenistan: "tm",
  Tuvalu: "tv",
  "Republic of Uganda": "ug",
  Ukraine: "ua",
  "United Arab Emirates": "ae",
  "United Kingdom of Great Britain and Northern Ireland": "gb",
  "United Republic of Tanzania": "tz",
  "United States of America": "us",
  "Oriental Republic of Uruguay": "uy",
  "Republic of Uzbekistan": "uz",
  "Republic of Vanuatu": "vu",
  "Bolivarian Republic of Venezuela": "ve",
  "Socialist Republic of Viet Nam": "vn",
  "Republic of Yemen": "ye",
  "Republic of Zambia": "zm",
  "Republic of Zimbabwe": "zw",
  // Observer States
  "Holy See": "va",
  "State of Palestine": "ps",
  // Dependent Territories
  "Christmas Island": "cx",
  "Cocos (Keeling) Islands": "cc",
  "Norfolk Island": "nf",
  "Hong Kong SAR": "hk",
  "Macao SAR": "mo",
  "Faroe Islands": "fo",
  Greenland: "gl",
  Åland: "ax",
  "French Guiana": "gf",
  "French Polynesia": "pf",
  Guadeloupe: "gp",
  Martinique: "mq",
  Mayotte: "yt",
  "New Caledonia": "nc",
  Réunion: "re",
  "Saint Barthelemy": "bl",
  "Saint Martin": "mf",
  "Saint-Pierre and Miquelon": "pm",
  "Wallis and Futuna": "wf",
  Aruba: "aw",
  Bonaire: "bq",
  Curaçao: "cw",
  Saba: "bq",
  "Sint Eustatius": "bq",
  "Sint Maarten": "sx",
  "Cook Islands": "ck",
  Niue: "nu",
  Tokelau: "tk",
  Svalbard: "sj",
  Anguilla: "ai",
  Bermuda: "bm",
  "British Virgin Islands": "vg",
  "Cayman Islands": "ky",
  "Falkland Islands": "fk",
  Gibraltar: "gi",
  Guernsey: "gg",
  "Isle of Man": "im",
  Jersey: "je",
  Montserrat: "ms",
  "Pitcairn Islands": "pn",
  "Saint Helena": "sh",
  "Turks and Caicos Islands": "tc",
  "American Samoa": "as",
  Guam: "gu",
  "Northern Mariana Islands": "mp",
  "Puerto Rico": "pr",
  "U.S. Virgin Islands": "vi",
  // Partially Recognized - use unique codes, don't inherit from parent countries
  "Republic of Abkhazia": "xx-ab", // No ISO code
  "Republic of China (Taiwan)": "tw",
  "Republic of Kosovo": "xk",
  "Turkish Republic of Northern Cyprus": "xx-nc", // No ISO code
  "Pridnestrovian Moldovan Republic (Transnistria)": "xx-tr", // No ISO code
  "Sahrawi Arab Democratic Republic (Western Sahara)": "eh",
  "Republic of Somaliland": "xx-sl", // No ISO code
  "Republic of South Ossetia (State of Alania)": "xx-so", // No ISO code
};

// Map A2 codes to A3 codes for visited check
const A2_TO_A3: Record<string, string> = {
  af: "AFG",
  al: "ALB",
  dz: "DZA",
  ad: "AND",
  ao: "AGO",
  ag: "ATG",
  ar: "ARG",
  am: "ARM",
  au: "AUS",
  at: "AUT",
  az: "AZE",
  bs: "BHS",
  bh: "BHR",
  bd: "BGD",
  bb: "BRB",
  by: "BLR",
  be: "BEL",
  bz: "BLZ",
  bj: "BEN",
  bt: "BTN",
  bo: "BOL",
  ba: "BIH",
  bw: "BWA",
  br: "BRA",
  bn: "BRN",
  bg: "BGR",
  bf: "BFA",
  bi: "BDI",
  kh: "KHM",
  cm: "CMR",
  ca: "CAN",
  cv: "CPV",
  cf: "CAF",
  td: "TCD",
  cl: "CHL",
  cn: "CHN",
  co: "COL",
  km: "COM",
  cg: "COG",
  cr: "CRI",
  ci: "CIV",
  hr: "HRV",
  cu: "CUB",
  cy: "CYP",
  cz: "CZE",
  kp: "PRK",
  cd: "COD",
  dk: "DNK",
  dj: "DJI",
  dm: "DMA",
  do: "DOM",
  ec: "ECU",
  eg: "EGY",
  sv: "SLV",
  gq: "GNQ",
  er: "ERI",
  ee: "EST",
  sz: "SWZ",
  et: "ETH",
  fj: "FJI",
  fi: "FIN",
  fr: "FRA",
  ga: "GAB",
  gm: "GMB",
  ge: "GEO",
  de: "DEU",
  gh: "GHA",
  gr: "GRC",
  gd: "GRD",
  gt: "GTM",
  gn: "GIN",
  gw: "GNB",
  gy: "GUY",
  ht: "HTI",
  hn: "HND",
  hu: "HUN",
  is: "ISL",
  in: "IND",
  id: "IDN",
  ir: "IRN",
  iq: "IRQ",
  ie: "IRL",
  il: "ISR",
  it: "ITA",
  jm: "JAM",
  jp: "JPN",
  jo: "JOR",
  kz: "KAZ",
  ke: "KEN",
  ki: "KIR",
  kw: "KWT",
  kg: "KGZ",
  la: "LAO",
  lv: "LVA",
  lb: "LBN",
  ls: "LSO",
  lr: "LBR",
  ly: "LBY",
  li: "LIE",
  lt: "LTU",
  lu: "LUX",
  mg: "MDG",
  mw: "MWI",
  my: "MYS",
  mv: "MDV",
  ml: "MLI",
  mt: "MLT",
  mh: "MHL",
  mr: "MRT",
  mu: "MUS",
  mx: "MEX",
  fm: "FSM",
  mc: "MCO",
  mn: "MNG",
  me: "MNE",
  ma: "MAR",
  mz: "MOZ",
  mm: "MMR",
  na: "NAM",
  nr: "NRU",
  np: "NPL",
  nl: "NLD",
  nz: "NZL",
  ni: "NIC",
  ne: "NER",
  ng: "NGA",
  mk: "MKD",
  no: "NOR",
  om: "OMN",
  pk: "PAK",
  pw: "PLW",
  pa: "PAN",
  pg: "PNG",
  py: "PRY",
  pe: "PER",
  ph: "PHL",
  pl: "POL",
  pt: "PRT",
  qa: "QAT",
  kr: "KOR",
  md: "MDA",
  ro: "ROU",
  ru: "RUS",
  rw: "RWA",
  kn: "KNA",
  lc: "LCA",
  vc: "VCT",
  ws: "WSM",
  sm: "SMR",
  st: "STP",
  sa: "SAU",
  sn: "SEN",
  rs: "SRB",
  sc: "SYC",
  sl: "SLE",
  sg: "SGP",
  sk: "SVK",
  si: "SVN",
  sb: "SLB",
  so: "SOM",
  za: "ZAF",
  ss: "SSD",
  es: "ESP",
  lk: "LKA",
  sd: "SDN",
  sr: "SUR",
  se: "SWE",
  ch: "CHE",
  sy: "SYR",
  tj: "TJK",
  th: "THA",
  tl: "TLS",
  tg: "TGO",
  to: "TON",
  tt: "TTO",
  tn: "TUN",
  tr: "TUR",
  tm: "TKM",
  tv: "TUV",
  ug: "UGA",
  ua: "UKR",
  ae: "ARE",
  gb: "GBR",
  tz: "TZA",
  us: "USA",
  uy: "URY",
  uz: "UZB",
  vu: "VUT",
  ve: "VEN",
  vn: "VNM",
  ye: "YEM",
  zm: "ZMB",
  zw: "ZWE",
  va: "VAT",
  ps: "PSE",
  cx: "CXR",
  cc: "CCK",
  nf: "NFK",
  hk: "HKG",
  mo: "MAC",
  fo: "FRO",
  gl: "GRL",
  ax: "ALA",
  gf: "GUF",
  pf: "PYF",
  gp: "GLP",
  mq: "MTQ",
  yt: "MYT",
  nc: "NCL",
  re: "REU",
  bl: "BLM",
  mf: "MAF",
  pm: "SPM",
  wf: "WLF",
  aw: "ABW",
  bq: "BES",
  cw: "CUW",
  sx: "SXM",
  ck: "COK",
  nu: "NIU",
  tk: "TKL",
  sj: "SJM",
  ai: "AIA",
  bm: "BMU",
  vg: "VGB",
  ky: "CYM",
  fk: "FLK",
  gi: "GIB",
  gg: "GGY",
  im: "IMN",
  je: "JEY",
  ms: "MSR",
  pn: "PCN",
  sh: "SHN",
  tc: "TCA",
  as: "ASM",
  gu: "GUM",
  mp: "MNP",
  pr: "PRI",
  vi: "VIR",
  tw: "TWN",
  xk: "XKX",
  eh: "ESH",
};

const SHORT_NAMES_RU: Record<string, string> = {
  Afghanistan: "Афганистан",
  Albania: "Албания",
  Algeria: "Алжир",
  Andorra: "Андорра",
  Angola: "Ангола",
  "Antigua and Barbuda": "Антигуа и Барбуда",
  Argentina: "Аргентина",
  Armenia: "Армения",
  Australia: "Австралия",
  Austria: "Австрия",
  Azerbaijan: "Азербайджан",
  Bahamas: "Багамы",
  Bahrain: "Бахрейн",
  Bangladesh: "Бангладеш",
  Barbados: "Барбадос",
  Belarus: "Беларусь",
  Belgium: "Бельгия",
  Belize: "Белиз",
  Benin: "Бенин",
  Bhutan: "Бутан",
  Bolivia: "Боливия",
  "Bosnia and Herzegovina": "Босния и Герцеговина",
  Botswana: "Ботсвана",
  Brazil: "Бразилия",
  Brunei: "Бруней",
  Bulgaria: "Болгария",
  "Burkina Faso": "Буркина-Фасо",
  Burundi: "Бурунди",
  Cambodia: "Камбоджа",
  Cameroon: "Камерун",
  Canada: "Канада",
  "Cabo Verde": "Кабо-Верде",
  "Central African Republic": "ЦАР",
  Chad: "Чад",
  Chile: "Чили",
  China: "Китай",
  Colombia: "Колумбия",
  Comoros: "Коморы",
  Congo: "Конго",
  "Costa Rica": "Коста-Рика",
  "Côte d'Ivoire": "Кот-д'Ивуар",
  Croatia: "Хорватия",
  Cuba: "Куба",
  Cyprus: "Кипр",
  Czechia: "Чехия",
  "North Korea": "Северная Корея",
  "DR Congo": "ДР Конго",
  Denmark: "Дания",
  Djibouti: "Джибути",
  Dominica: "Доминика",
  "Dominican Republic": "Доминикана",
  Ecuador: "Эквадор",
  Egypt: "Египет",
  "El Salvador": "Сальвадор",
  "Equatorial Guinea": "Экваториальная Гвинея",
  Eritrea: "Эритрея",
  Estonia: "Эстония",
  Eswatini: "Эсватини",
  Ethiopia: "Эфиопия",
  Fiji: "Фиджи",
  Finland: "Финляндия",
  France: "Франция",
  Gabon: "Габон",
  Gambia: "Гамбия",
  Georgia: "Грузия",
  Germany: "Германия",
  Ghana: "Гана",
  Greece: "Греция",
  Grenada: "Гренада",
  Guatemala: "Гватемала",
  Guinea: "Гвинея",
  "Guinea-Bissau": "Гвинея-Бисау",
  Guyana: "Гайана",
  Haiti: "Гаити",
  Honduras: "Гондурас",
  Hungary: "Венгрия",
  Iceland: "Исландия",
  India: "Индия",
  Indonesia: "Индонезия",
  Iran: "Иран",
  Iraq: "Ирак",
  Ireland: "Ирландия",
  Israel: "Израиль",
  Italy: "Италия",
  Jamaica: "Ямайка",
  Japan: "Япония",
  Jordan: "Иордания",
  Kazakhstan: "Казахстан",
  Kenya: "Кения",
  Kiribati: "Кирибати",
  Kuwait: "Кувейт",
  Kyrgyzstan: "Киргизия",
  Laos: "Лаос",
  Latvia: "Латвия",
  Lebanon: "Ливан",
  Lesotho: "Лесото",
  Liberia: "Либерия",
  Libya: "Ливия",
  Liechtenstein: "Лихтенштейн",
  Lithuania: "Литва",
  Luxembourg: "Люксембург",
  Madagascar: "Мадагаскар",
  Malawi: "Малави",
  Malaysia: "Малайзия",
  Maldives: "Мальдивы",
  Mali: "Мали",
  Malta: "Мальта",
  "Marshall Islands": "Маршалловы Острова",
  Mauritania: "Мавритания",
  Mauritius: "Маврикий",
  Mexico: "Мексика",
  Micronesia: "Микронезия",
  Monaco: "Монако",
  Mongolia: "Монголия",
  Montenegro: "Черногория",
  Morocco: "Марокко",
  Mozambique: "Мозамбик",
  Myanmar: "Мьянма",
  Namibia: "Намибия",
  Nauru: "Науру",
  Nepal: "Непал",
  Netherlands: "Нидерланды",
  "New Zealand": "Новая Зеландия",
  Nicaragua: "Никарагуа",
  Niger: "Нигер",
  Nigeria: "Нигерия",
  "North Macedonia": "Северная Македония",
  Norway: "Норвегия",
  Oman: "Оман",
  Pakistan: "Пакистан",
  Palau: "Палау",
  Panama: "Панама",
  "Papua New Guinea": "Папуа — Новая Гвинея",
  Paraguay: "Парагвай",
  Peru: "Перу",
  Philippines: "Филиппины",
  Poland: "Польша",
  Portugal: "Португалия",
  Qatar: "Катар",
  "South Korea": "Южная Корея",
  Moldova: "Молдова",
  Romania: "Румыния",
  Russia: "Россия",
  Rwanda: "Руанда",
  "Saint Kitts and Nevis": "Сент-Китс и Невис",
  "Saint Lucia": "Сент-Люсия",
  "Saint Vincent and the Grenadines": "Сент-Винсент и Гренадины",
  Samoa: "Самоа",
  "San Marino": "Сан-Марино",
  "São Tomé and Príncipe": "Сан-Томе и Принсипи",
  "Saudi Arabia": "Саудовская Аравия",
  Senegal: "Сенегал",
  Serbia: "Сербия",
  Seychelles: "Сейшелы",
  "Sierra Leone": "Сьерра-Леоне",
  Singapore: "Сингапур",
  Slovakia: "Словакия",
  Slovenia: "Словения",
  "Solomon Islands": "Соломоновы Острова",
  Somalia: "Сомали",
  "South Africa": "ЮАР",
  "South Sudan": "Южный Судан",
  Spain: "Испания",
  "Sri Lanka": "Шри-Ланка",
  Sudan: "Судан",
  Suriname: "Суринам",
  Sweden: "Швеция",
  Switzerland: "Швейцария",
  Syria: "Сирия",
  Tajikistan: "Таджикистан",
  Thailand: "Таиланд",
  "Timor-Leste": "Восточный Тимор",
  Togo: "Того",
  Tonga: "Тонга",
  "Trinidad and Tobago": "Тринидад и Тобаго",
  Tunisia: "Тунис",
  Türkiye: "Турция",
  Turkmenistan: "Туркменистан",
  Tuvalu: "Тувалу",
  Uganda: "Уганда",
  Ukraine: "Украина",
  UAE: "ОАЭ",
  "United Kingdom": "Великобритания",
  Tanzania: "Танзания",
  "United States": "США",
  Uruguay: "Уругвай",
  Uzbekistan: "Узбекистан",
  Vanuatu: "Вануату",
  Venezuela: "Венесуэла",
  Vietnam: "Вьетнам",
  Yemen: "Йемен",
  Zambia: "Замбия",
  Zimbabwe: "Зимбабве",
  Palestine: "Палестина",
  Vatican: "Ватикан",
  "Hong Kong": "Гонконг",
  Macao: "Макао",
  "Christmas Island": "Остров Рождества",
  "Cocos (Keeling) Islands": "Кокосовые острова",
  "Norfolk Island": "Остров Норфолк",
  "Faroe Islands": "Фарерские острова",
  Greenland: "Гренландия",
  Åland: "Аландские острова",
  "French Guiana": "Французская Гвиана",
  "French Polynesia": "Французская Полинезия",
  Guadeloupe: "Гваделупа",
  Martinique: "Мартиника",
  Mayotte: "Майотта",
  "New Caledonia": "Новая Каледония",
  Réunion: "Реюньон",
  "Saint Barthelemy": "Сен-Бартелеми",
  "Saint Martin": "Сен-Мартен",
  "Saint-Pierre and Miquelon": "Сен-Пьер и Микелон",
  "Wallis and Futuna": "Уоллис и Футуна",
  Aruba: "Аруба",
  Bonaire: "Бонэйр",
  Curaçao: "Кюрасао",
  Saba: "Саба",
  "Sint Eustatius": "Синт-Эстатиус",
  "Sint Maarten": "Синт-Мартен",
  "Cook Islands": "Острова Кука",
  Niue: "Ниуэ",
  Tokelau: "Токелау",
  Svalbard: "Шпицберген",
  Anguilla: "Ангилья",
  Bermuda: "Бермуды",
  "British Virgin Islands": "Британские Виргинские острова",
  "Cayman Islands": "Каймановы острова",
  "Falkland Islands": "Фолклендские острова",
  Gibraltar: "Гибралтар",
  Guernsey: "Гернси",
  "Isle of Man": "Остров Мэн",
  Jersey: "Джерси",
  Montserrat: "Монтсеррат",
  "Pitcairn Islands": "Острова Питкэрн",
  "Saint Helena": "Остров Святой Елены",
  "Turks and Caicos Islands": "Тёркс и Кайкос",
  "American Samoa": "Американское Самоа",
  Guam: "Гуам",
  "Northern Mariana Islands": "Северные Марианские острова",
  "Puerto Rico": "Пуэрто-Рико",
  "U.S. Virgin Islands": "Американские Виргинские острова",
  Abkhazia: "Абхазия",
  Taiwan: "Тайвань",
  Kosovo: "Косово",
  "Northern Cyprus": "Северный Кипр",
  Transnistria: "Приднестровье",
  "Western Sahara": "Западная Сахара",
  Somaliland: "Сомалиленд",
  "South Ossetia": "Южная Осетия",
};

const CATEGORY_NAMES: Record<CategoryId, { en: string; ru: string }> = {
  "member-states": { en: "Member States", ru: "Государства-члены ООН" },
  "observer-states": {
    en: "Observer States",
    ru: "Государства-наблюдатели",
  },
  "dependent-territories": {
    en: "Dependent Territories",
    ru: "Зависимые территории",
  },
  "partially-recognized": {
    en: "Partially Recognized States",
    ru: "Частично признанные государства",
  },
};

function parseCountriesMarkdown(): ParsedSection[] {
  const content = countryList.rawContent();
  const sections: ParsedSection[] = [];

  // Split by ## headers
  const parts = content.split(/^## /m).filter(Boolean);

  for (const part of parts) {
    const lines = part.trim().split("\n");
    const headerLine = lines[0];

    let categoryId: CategoryId | null = null;
    if (headerLine.includes("Member States")) {
      categoryId = "member-states";
    } else if (headerLine.includes("Observer States")) {
      categoryId = "observer-states";
    } else if (headerLine.includes("Dependent Territories")) {
      categoryId = "dependent-territories";
    } else if (headerLine.includes("Partially Recognized")) {
      categoryId = "partially-recognized";
    }

    if (!categoryId) continue;

    const countries: string[] = [];

    for (const line of lines.slice(1)) {
      // Match numbered list items: "1. Country Name"
      const match = line.match(/^\d+\.\s+(.+)$/);
      if (match) {
        countries.push(match[1].trim());
      }
    }

    sections.push({
      id: categoryId,
      name: CATEGORY_NAMES[categoryId].en,
      nameRu: CATEGORY_NAMES[categoryId].ru,
      countries,
    });
  }

  return sections;
}

function isCountryVisited(officialName: string): boolean {
  const a2 = NAME_TO_A2[officialName];
  if (!a2) return false;

  const a3 = A2_TO_A3[a2];
  if (!a3) return false;

  return visitedCountryCodes.has(a3);
}

function getCountryA2(officialName: string): string {
  return NAME_TO_A2[officialName] || "";
}

function getShortName(officialName: string): string {
  return SHORT_NAMES[officialName] || officialName;
}

function getShortNameRu(officialName: string): string {
  const shortEn = getShortName(officialName);
  return SHORT_NAMES_RU[shortEn] || shortEn;
}

export function getChecklist(): ChecklistCategory[] {
  const sections = parseCountriesMarkdown();

  return sections.map((section) => ({
    id: section.id,
    name: section.name,
    nameRu: section.nameRu,
    countries: section.countries.map((name) => ({
      name,
      nameShort: getShortName(name),
      nameShortRu: getShortNameRu(name),
      a2: getCountryA2(name),
      visited: isCountryVisited(name),
    })),
  }));
}

export function getChecklistStats(): {
  total: number;
  visited: number;
  byCategory: Record<CategoryId, { total: number; visited: number }>;
} {
  const checklist = getChecklist();

  const byCategory = {} as Record<
    CategoryId,
    { total: number; visited: number }
  >;
  let total = 0;
  let visited = 0;

  for (const category of checklist) {
    const categoryVisited = category.countries.filter((c) => c.visited).length;
    byCategory[category.id] = {
      total: category.countries.length,
      visited: categoryVisited,
    };
    total += category.countries.length;
    visited += categoryVisited;
  }

  return { total, visited, byCategory };
}
