type Continent =
  | "Africa"
  | "Asia"
  | "Europe"
  | "North America"
  | "South America"
  | "Australia"
  | "Antartica";
type Status = "UNM" | "UNNMO" | "DT" | "UNNM";

interface Country {
  name: string;
  officialName: string;
  continent?: Continent;
  A2: string;
  A3: string;
  status?: Status;
}

const countries: Country[] = [
  {
    A2: "AF",
    A3: "AFG",
    continent: "Asia",
    name: "Afghanistan",
    officialName: "Islamic Republic of Afghanistan",
  },
  {
    A2: "AL",
    A3: "ALB",
    continent: "Europe",
    name: "Albania",
    officialName: "Republic of Albania",
  },
  {
    A2: "DZ",
    A3: "DZA",
    continent: "Africa",
    name: "Algeria",
    officialName: "People’s Democratic Republic of Algeria",
  },
  {
    A2: "AD",
    A3: "AND",
    continent: "Europe",
    name: "Andorra",
    officialName: "Principality of Andorra",
  },
  {
    A2: "AO",
    A3: "AGO",
    continent: "Africa",
    name: "Angola",
    officialName: "Republic of Angola",
  },
  {
    A2: "AG",
    A3: "ATG",
    continent: undefined,
    name: "Antigua and Barbuda",
    officialName: "Antigua and Barbuda",
  },
  {
    A2: "AR",
    A3: "ARG",
    continent: "South America",
    name: "Argentina",
    officialName: "Republic of Argentina",
  },
  {
    A2: "AM",
    A3: "ARM",
    continent: "Asia",
    name: "Armenia",
    officialName: "Republic of Armenia",
  },
  {
    A2: "AU",
    A3: "AUS",
    continent: "Australia",
    name: "Australia",
    officialName: "Commonwealth of Australia",
  },
  {
    A2: "AT",
    A3: "AUT",
    continent: "Europe",
    name: "Austria",
    officialName: "Republic of Austria",
  },
  {
    A2: "AZ",
    A3: "AZE",
    continent: "Asia",
    name: "Azerbaijan",
    officialName: "Republic of Azerbaijan",
  },
  {
    A2: "BS",
    A3: "BHS",
    continent: undefined,
    name: "Bahamas",
    officialName: "Commonwealth of the Bahamas",
  },
  {
    A2: "BH",
    A3: "BHR",
    continent: "Asia",
    name: "Bahrain",
    officialName: "Kingdom of Bahrain",
  },
  {
    A2: "BD",
    A3: "BGD",
    continent: "Asia",
    name: "Bangladesh",
    officialName: "People’s Republic of Bangladesh",
  },
  {
    A2: "BB",
    A3: "BRB",
    continent: undefined,
    name: "Barbados",
    officialName: "Barbados",
  },
  {
    A2: "BY",
    A3: "BLR",
    continent: "Europe",
    name: "Belarus",
    officialName: "Republic of Belarus",
  },
  {
    A2: "BE",
    A3: "BEL",
    continent: "Europe",
    name: "Belgium",
    officialName: "Kingdom of Belgium",
  },
  {
    A2: "BZ",
    A3: "BLZ",
    continent: "North America",
    name: "Belize",
    officialName: "Belize",
  },
  {
    A2: "BJ",
    A3: "BEN",
    continent: "Africa",
    name: "Benin",
    officialName: "Republic of Benin",
  },
  {
    A2: "BT",
    A3: "BTN",
    continent: "Asia",
    name: "Bhutan",
    officialName: "Kingdom of Bhutan",
  },
  {
    A2: "BO",
    A3: "BOL",
    continent: "South America",
    name: "Bolivia",
    officialName: "Plurinational State of Bolivia (Plurinational State of)",
  },
  {
    A2: "BA",
    A3: "BIH",
    continent: "Europe",
    name: "Bosnia and Herzegovina",
    officialName: "Bosnia and Herzegovina",
  },
  {
    A2: "BW",
    A3: "BWA",
    continent: "Africa",
    name: "Botswana",
    officialName: "Republic of Botswana",
  },
  {
    A2: "BR",
    A3: "BRA",
    continent: "South America",
    name: "Brazil",
    officialName: "Federative Republic of Brazil",
  },
  {
    A2: "BN",
    A3: "BRN",
    continent: "Asia",
    name: "Brunei",
    officialName: "Negara Brunei Darussalam",
  },
  {
    A2: "BG",
    A3: "BGR",
    continent: "Europe",
    name: "Bulgaria",
    officialName: "Republic of Bulgaria",
  },
  {
    A2: "BF",
    A3: "BFA",
    continent: "Africa",
    name: "Burkina Faso",
    officialName: "Burkina Faso",
  },
  {
    A2: "BI",
    A3: "BDI",
    continent: "Africa",
    name: "Burundi",
    officialName: "Republic of Burundi",
  },
  {
    A2: "KH",
    A3: "KHM",
    continent: "Asia",
    name: "Cambodia",
    officialName: "Kingdom of Cambodia",
  },
  {
    A2: "CM",
    A3: "CMR",
    continent: "Africa",
    name: "Cameroon",
    officialName: "Republic of Cameroon",
  },
  {
    A2: "CA",
    A3: "CAN",
    continent: "North America",
    name: "Canada",
    officialName: "Canada",
  },
  {
    A2: "CV",
    A3: "CPV",
    continent: "Africa",
    name: "Cabo Verde",
    officialName: "Republic of Cabo Verde",
  },
  {
    A2: "CF",
    A3: "CAF",
    continent: "Africa",
    name: "Central African Republic",
    officialName: "Central African Republic",
  },
  {
    A2: "TD",
    A3: "TCD",
    continent: "Africa",
    name: "Chad",
    officialName: "Republic of Chad",
  },
  {
    A2: "CL",
    A3: "CHL",
    continent: "South America",
    name: "Chile",
    officialName: "Republic of Chile",
  },
  {
    A2: "CN",
    A3: "CHN",
    continent: "Asia",
    name: "China",
    officialName: "People’s Republic of China",
  },
  {
    A2: "CO",
    A3: "COL",
    continent: "South America",
    name: "Colombia",
    officialName: "Republic of Colombia",
  },
  {
    A2: "KM",
    A3: "COM",
    continent: "Africa",
    name: "Comoros",
    officialName: "Union of the Comoros",
  },
  {
    A2: "CG",
    A3: "COG",
    continent: "Africa",
    name: "Republic of the Congo",
    officialName: "Republic of the Congo",
  },
  {
    A2: "CR",
    A3: "CRI",
    continent: "North America",
    name: "Costa Rica",
    officialName: "Republic of Costa Rica",
  },
  {
    A2: "CI",
    A3: "CIV",
    continent: "Africa",
    name: "Côte d’Ivoire",
    officialName: "Republic of Côte d’Ivoire",
  },
  {
    A2: "HR",
    A3: "HRV",
    continent: "Europe",
    name: "Croatia",
    officialName: "Republic of Croatia",
  },
  {
    A2: "CU",
    A3: "CUB",
    continent: "North America",
    name: "Cuba",
    officialName: "Republic of Cuba",
  },
  {
    A2: "CY",
    A3: "CYP",
    continent: "Europe",
    name: "Cyprus",
    officialName: "Republic of Cyprus",
  },
  {
    A2: "CZ",
    A3: "CZE",
    continent: "Europe",
    name: "Czech Republic (Czechia)",
    officialName: "Czech Republic (Czechia)",
  },
  {
    A2: "KP",
    A3: "PRK",
    continent: "Asia",
    name: "North Korea",
    officialName: "Democratic People’s Republic of Korea",
  },
  {
    A2: "CD",
    A3: "COD",
    continent: "Africa",
    name: "Democratic Republic of the Congo",
    officialName: "Democratic Republic of the Congo",
  },
  {
    A2: "DK",
    A3: "DNK",
    continent: "Europe",
    name: "Denmark",
    officialName: "Kingdom of Denmark",
  },
  {
    A2: "DJ",
    A3: "DJI",
    continent: "Africa",
    name: "Djibouti",
    officialName: "Republic of Djibouti",
  },
  {
    A2: "DM",
    A3: "DMA",
    continent: undefined,
    name: "Dominica",
    officialName: "Commonwealth of Dominica",
  },
  {
    A2: "DO",
    A3: "DOM",
    continent: "North America",
    name: "Dominican Republic",
    officialName: "Dominican Republic",
  },
  {
    A2: "EC",
    A3: "ECU",
    continent: "South America",
    name: "Ecuador",
    officialName: "Republic of Ecuador",
  },
  {
    A2: "EG",
    A3: "EGY",
    continent: "Africa",
    name: "Egypt",
    officialName: "Arab Republic of Egypt",
  },
  {
    A2: "SV",
    A3: "SLV",
    continent: "North America",
    name: "El Salvador",
    officialName: "Republic of El Salvador",
  },
  {
    A2: "GQ",
    A3: "GNQ",
    continent: "Africa",
    name: "Equatorial Guinea",
    officialName: "Republic of Equatorial Guinea",
  },
  {
    A2: "ER",
    A3: "ERI",
    continent: "Africa",
    name: "Eritrea",
    officialName: "State of Eritrea",
  },
  {
    A2: "EE",
    A3: "EST",
    continent: "Europe",
    name: "Estonia",
    officialName: "Republic of Estonia",
  },
  {
    A2: "SZ",
    A3: "SWZ",
    continent: "Africa",
    name: "Eswatini",
    officialName: "Kingdom of Eswatini",
  },
  {
    A2: "ET",
    A3: "ETH",
    continent: "Africa",
    name: "Ethiopia",
    officialName: "Federal Democratic Republic of Ethiopia",
  },
  {
    A2: "FJ",
    A3: "FJI",
    continent: undefined,
    name: "Fiji",
    officialName: "Republic of Fiji",
  },
  {
    A2: "FI",
    A3: "FIN",
    continent: "Europe",
    name: "Finland",
    officialName: "Republic of Finland",
  },
  {
    A2: "FR",
    A3: "FRA",
    continent: "Europe",
    name: "France",
    officialName: "Republic of France",
  },
  {
    A2: "GA",
    A3: "GAB",
    continent: "Africa",
    name: "Gabon",
    officialName: "Gabonese Republic (Gabon)",
  },
  {
    A2: "GM",
    A3: "GMB",
    continent: "Africa",
    name: "Gambia",
    officialName: "Republic of The Gambia",
  },
  {
    A2: "GE",
    A3: "GEO",
    continent: "Asia",
    name: "Georgia",
    officialName: "Georgia",
  },
  {
    A2: "DE",
    A3: "DEU",
    continent: "Europe",
    name: "Germany",
    officialName: "Federal Republic of Germany",
  },
  {
    A2: "GH",
    A3: "GHA",
    continent: "Africa",
    name: "Ghana",
    officialName: "Republic of Ghana",
  },
  {
    A2: "GI",
    A3: "GIB",
    continent: "Europe",
    name: "Greece",
    officialName: "Hellenic Republic (Greece)",
  },
  {
    A2: "GD",
    A3: "GRD",
    continent: undefined,
    name: "Grenada",
    officialName: "Grenada",
  },
  {
    A2: "GT",
    A3: "GTM",
    continent: "North America",
    name: "Guatemala",
    officialName: "Republic of Guatemala",
  },
  {
    A2: "GN",
    A3: "GIN",
    continent: "Africa",
    name: "Guinea",
    officialName: "Republic of Guinea",
  },
  {
    A2: "GW",
    A3: "GNB",
    continent: "Africa",
    name: "Guinea-Bissau",
    officialName: "Republic of Guinea-Bissau",
  },
  {
    A2: "GY",
    A3: "GUY",
    continent: "South America",
    name: "Guyana",
    officialName: "Co-operative Republic of Guyana",
  },
  {
    A2: "HT",
    A3: "HTI",
    continent: "North America",
    name: "Haiti",
    officialName: "Republic of Haiti",
  },
  {
    A2: "HN",
    A3: "HND",
    continent: "North America",
    name: "Honduras",
    officialName: "Republic of Honduras",
  },
  {
    A2: "HU",
    A3: "HUN",
    continent: "Europe",
    name: "Hungary",
    officialName: "Hungary",
  },
  {
    A2: "IS",
    A3: "ISL",
    continent: "Europe",
    name: "Iceland",
    officialName: "Iceland",
  },
  {
    A2: "IN",
    A3: "IND",
    continent: "Asia",
    name: "India",
    officialName: "Republic of India",
  },
  {
    A2: "ID",
    A3: "IDN",
    continent: "Asia",
    name: "Indonesia",
    officialName: "Republic of Indonesia",
  },
  {
    A2: "IR",
    A3: "IRN",
    continent: "Asia",
    name: "Iran",
    officialName: "Islamic Republic of Iran (Islamic Republic of)",
  },
  {
    A2: "IQ",
    A3: "IRQ",
    continent: "Asia",
    name: "Iraq",
    officialName: "Republic of Iraq",
  },
  {
    A2: "IE",
    A3: "IRL",
    continent: "Europe",
    name: "Ireland",
    officialName: "Ireland",
  },
  {
    A2: "IL",
    A3: "ISR",
    continent: "Asia",
    name: "Israel",
    officialName: "State of Israel",
  },
  {
    A2: "IT",
    A3: "ITA",
    continent: "Europe",
    name: "Italy",
    officialName: "Republic of Italy",
  },
  {
    A2: "JM",
    A3: "JAM",
    continent: "North America",
    name: "Jamaica",
    officialName: "Jamaica",
  },
  {
    A2: "JP",
    A3: "JPN",
    continent: "Asia",
    name: "Japan",
    officialName: "Japan",
  },
  {
    A2: "JO",
    A3: "JOR",
    continent: "Asia",
    name: "Jordan",
    officialName: "Hashemite Kingdom of Jordan",
  },
  {
    A2: "KZ",
    A3: "KAZ",
    continent: "Asia",
    name: "Kazakhstan",
    officialName: "Republic of Kazakhstan",
  },
  {
    A2: "KE",
    A3: "KEN",
    continent: "Africa",
    name: "Kenya",
    officialName: "Republic of Kenya",
  },
  {
    A2: "KI",
    A3: "KIR",
    continent: undefined,
    name: "Kiribati",
    officialName: "Republic of Kiribati",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Asia",
    name: "Kuwait",
    officialName: "State of Kuwait",
  },
  {
    A2: "KG",
    A3: "KGZ",
    continent: "Asia",
    name: "Kyrgyzstan",
    officialName: "Kyrgyz Republic (Kyrgyzstan)",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Asia",
    name: "Laos",
    officialName: "Lao People’s Democratic Republic",
  },
  {
    A2: "LV",
    A3: "LVA",
    continent: "Europe",
    name: "Latvia",
    officialName: "Republic of Latvia",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Asia",
    name: "Lebanon",
    officialName: "Republic of Lebanon",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Lesotho",
    officialName: "Kingdom of Lesotho",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Liberia",
    officialName: "Republic of Liberia",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Libya",
    officialName: "State of Libya",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Europe",
    name: "Liechtenstein",
    officialName: "Principality of Liechtenstein",
  },
  {
    A2: "LT",
    A3: "LTU",
    continent: "Europe",
    name: "Lithuania",
    officialName: "Republic of Lithuania",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Europe",
    name: "Luxembourg",
    officialName: "Grand Duchy of Luxembourg",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Madagascar",
    officialName: "Republic of Madagascar",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Malawi",
    officialName: "Republic of Malawi",
  },
  {
    A2: "MY",
    A3: "MYS",
    continent: "Asia",
    name: "Malaysia",
    officialName: "Malaysia",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: undefined,
    name: "Maldives",
    officialName: "Republic of Maldives",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Mali",
    officialName: "Republic of Mali",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Europe",
    name: "Malta",
    officialName: "Republic of Malta",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Marshall Islands",
    officialName: "Republic of the Marshall Islands",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Mauritania",
    officialName: "Islamic Republic of Mauritania",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Mauritius",
    officialName: "Republic of Mauritius",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "North America",
    name: "Mexico",
    officialName: "United Mexican States (Mexico)",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: undefined,
    name: "Micronesia",
    officialName: "Federated States of Micronesia (Federated States of)",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Europe",
    name: "Monaco",
    officialName: "Principality of Monaco",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Asia",
    name: "Mongolia",
    officialName: "Mongolia",
  },
  {
    A2: "ME",
    A3: "MNE",
    continent: "Europe",
    name: "Montenegro",
    officialName: "Montenegro",
  },
  {
    A2: "MA",
    A3: "MAR",
    continent: "Africa",
    name: "Morocco",
    officialName: "Kingdom of Morocco",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Mozambique",
    officialName: "Republic of Mozambique",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Asia",
    name: "Myanmar",
    officialName: "Republic of the Union of Myanmar",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Namibia",
    officialName: "Republic of Namibia",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: undefined,
    name: "Nauru",
    officialName: "Republic of Nauru",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Asia",
    name: "Nepal",
    officialName: "Nepal",
  },
  {
    A2: "NL",
    A3: "NLD",
    continent: "Europe",
    name: "Netherlands",
    officialName: "Kingdom of the Netherlands (Kingdom of the)",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "New Zealand",
    officialName: "New Zealand",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "North America",
    name: "Nicaragua",
    officialName: "Republic of Nicaragua",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Niger",
    officialName: "Republic of the Niger",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Nigeria",
    officialName: "Federal Republic of Nigeria",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Europe",
    name: "North Macedonia",
    officialName: "Republic of North Macedonia",
  },
  {
    A2: "NO",
    A3: "NOR",
    continent: "Europe",
    name: "Norway",
    officialName: "Kingdom of Norway",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Asia",
    name: "Oman",
    officialName: "Sultanate of Oman",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Asia",
    name: "Pakistan",
    officialName: "Islamic Republic of Pakistan",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: undefined,
    name: "Palau",
    officialName: "Republic of Palau",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "North America",
    name: "Panama",
    officialName: "Republic of Panama",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: undefined,
    name: "Papua New Guinea",
    officialName: "Independent State of Papua New Guinea",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "South America",
    name: "Paraguay",
    officialName: "Republic of Paraguay",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "South America",
    name: "Peru",
    officialName: "Republic of Peru",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Asia",
    name: "Philippines",
    officialName: "Republic of the Philippines",
  },
  {
    A2: "PL",
    A3: "POL",
    continent: "Europe",
    name: "Poland",
    officialName: "Republic of Poland",
  },
  {
    A2: "PT",
    A3: "PRT",
    continent: "Europe",
    name: "Portugal",
    officialName: "Portuguese Republic (Portugal)",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Asia",
    name: "Qatar",
    officialName: "State of Qatar",
  },
  {
    A2: "KR",
    A3: "KOR",
    continent: "Asia",
    name: "South Korea",
    officialName: "Republic of Korea",
  },
  {
    A2: "MD",
    A3: "MDA",
    continent: "Europe",
    name: "Moldova",
    officialName: "Republic of Moldova",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Europe",
    name: "Romania",
    officialName: "Romania",
  },
  {
    A2: "RU",
    A3: "RUS",
    continent: "Asia",
    name: "Russia",
    officialName: "Russian Federation",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Rwanda",
    officialName: "Republic of Rwanda",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: undefined,
    name: "Saint Kitts and Nevis",
    officialName: "Saint Kitts and Nevis",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: undefined,
    name: "Saint Lucia",
    officialName: "Saint Lucia",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: undefined,
    name: "Saint Vincent and the Grenadines",
    officialName: "Saint Vincent and the Grenadines",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: undefined,
    name: "Samoa",
    officialName: "Independent State of Samoa",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Europe",
    name: "San Marino",
    officialName: "Republic of San Marino",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Sao Tome and Principe",
    officialName: "Democratic Republic of Sao Tome and Principe",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Asia",
    name: "Saudi Arabia",
    officialName: "Kingdom of Saudi Arabia",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Senegal",
    officialName: "Republic of Senegal",
  },
  {
    A2: "RS",
    A3: "SRB",
    continent: "Europe",
    name: "Serbia",
    officialName: "Republic of Serbia",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Seychelles",
    officialName: "Republic of Seychelles",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Sierra Leone",
    officialName: "Republic of Sierra Leone",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Asia",
    name: "Singapore",
    officialName: "Republic of Singapore",
  },
  {
    A2: "SK",
    A3: "SVK",
    continent: "Europe",
    name: "Slovakia",
    officialName: "Slovak Republic (Slovakia)",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Europe",
    name: "Slovenia",
    officialName: "Republic of Slovenia",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: undefined,
    name: "Solomon Islands",
    officialName: "Solomon Islands",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Somalia",
    officialName: "Federal Republic of Somalia",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "South Africa",
    officialName: "Republic of South Africa",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "South Sudan",
    officialName: "Republic of South Sudan",
  },
  {
    A2: "ES",
    A3: "ESP",
    continent: "Europe",
    name: "Spain",
    officialName: "Kingdom of Spain",
  },
  {
    A2: "LK",
    A3: "LKA",
    continent: "Asia",
    name: "Sri Lanka",
    officialName: "Democratic Socialist Republic of Sri Lanka",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Sudan",
    officialName: "Republic of the Sudan",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "South America",
    name: "Suriname",
    officialName: "Republic of Suriname",
  },
  {
    A2: "SE",
    A3: "SWE",
    continent: "Europe",
    name: "Sweden",
    officialName: "Kingdom of Sweden",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Europe",
    name: "Switzerland",
    officialName: "Swiss Confederation (Switzerland)",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Asia",
    name: "Syria",
    officialName: "Syrian Arab Republic",
  },
  {
    A2: "TJ",
    A3: "TJK",
    continent: "Asia",
    name: "Tajikistan",
    officialName: "Republic of Tajikistan",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Asia",
    name: "Thailand",
    officialName: "Kingdom of Thailand",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Asia",
    name: "East Timor",
    officialName: "Democratic Republic of Timor-Leste",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Togo",
    officialName: "Republic of Togo",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: undefined,
    name: "Tonga",
    officialName: "Kingdom of Tonga",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: undefined,
    name: "Trinidad and Tobago",
    officialName: "Republic of Trinidad and Tobago",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Tunisia",
    officialName: "Republic of Tunisia",
  },
  {
    A2: "TR",
    A3: "TUR",
    continent: "Asia",
    name: "Turkey",
    officialName: "Republic of Türkiye",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Asia",
    name: "Turkmenistan",
    officialName: "Turkmenistan",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: undefined,
    name: "Tuvalu",
    officialName: "Tuvalu",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Uganda",
    officialName: "Republic of Uganda",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Europe",
    name: "Ukraine",
    officialName: "Ukraine",
  },
  {
    A2: "AE",
    A3: "ARE",
    continent: "Asia",
    name: "United Arab Emirates",
    officialName: "United Arab Emirates",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Europe",
    name: "United Kingdom",
    officialName: "United Kingdom of Great Britain and Northern Ireland",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Tanzania",
    officialName: "United Republic of Tanzania",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "North America",
    name: "United States",
    officialName: "United States of America",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "South America",
    name: "Uruguay",
    officialName: "Oriental Republic of Uruguay",
  },
  {
    A2: "UZ",
    A3: "UZB",
    continent: "Asia",
    name: "Uzbekistan",
    officialName: "Republic of Uzbekistan",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: undefined,
    name: "Vanuatu",
    officialName: "Republic of Vanuatu",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "South America",
    name: "Venezuela",
    officialName: "Bolivarian Republic of Venezuela",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Asia",
    name: "Vietnam",
    officialName: "Socialist Republic of Viet Nam",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Asia",
    name: "Yemen",
    officialName: "Republic of Yemen",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Zambia",
    officialName: "Republic of Zambia",
  },
  {
    A2: "XX",
    A3: "XXX",
    continent: "Africa",
    name: "Zimbabwe",
    officialName: "Republic of Zimbabwe",
  },
];

function toArray() {
  return countries;
}

function toSet() {
  return new Set(countries);
}

export function findMany(query: string) {
  const preparedQuery = query.trim().toLowerCase();
  return countries.filter((country) => {
    return (
      country.name.toLowerCase().includes(preparedQuery) ||
      country.officialName.toLowerCase().includes(preparedQuery)
    );
  });
}

export function findOne(query: string) {
  const preparedQuery = query.trim().toLowerCase();
  return countries.find((country) => {
    return (
      country.name.toLowerCase().includes(preparedQuery) ||
      country.officialName.toLowerCase().includes(preparedQuery)
    );
  });
}

export function getByCode(code: string) {
  const preparedCode = code.trim().toLowerCase();
  return countries.find((country) => {
    return (
      country.A2.toLowerCase() === preparedCode ||
      country.A3.toLowerCase() === preparedCode
    );
  });
}

export function getList() {
  return {
    toArray,
    toSet,
  };
}
